copy_hieradata: true
copy_puppet: true
manifest: /opt/system-config/production/manifests/site.pp
manifest_base: /opt/system-config
puppetdb: https://puppetdb.openstack.org:8081
puppet_logdest: syslog
