iptables_extra_allowed_hosts:
  - protocol: tcp
    port: 9200:9400
    hostname: elasticsearch02.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: elasticsearch03.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: elasticsearch04.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: elasticsearch05.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: elasticsearch06.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: elasticsearch07.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker01.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker02.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker03.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker04.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker05.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker06.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker07.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker08.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker09.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker10.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker11.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker12.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker13.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker14.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker15.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker16.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker17.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker18.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker19.openstack.org
  - protocol: tcp
    port: 9200:9400
    hostname: logstash-worker20.openstack.org
