iptables_extra_allowed_hosts:
  - hostname: bridge.openstack.org
    port: 8125
    protocol: udp
  - hostname: git.openstack.org
    port: 8125
    protocol: udp
  - hostname: firehose01.openstack.org
    port: 8125
    protocol: udp
  - hostname: mirror-update01.openstack.org
    port: 8125
    protocol: udp
  - hostname: logstash.openstack.org
    port: 8125
    protocol: udp
  - hostname: nb01.openstack.org
    port: 8125
    protocol: udp
  - hostname: nb02.openstack.org
    port: 8125
    protocol: udp
  - hostname: nb03.openstack.org
    port: 8125
    protocol: udp
  - hostname: nl01.openstack.org
    port: 8125
    protocol: udp
  - hostname: nl02.openstack.org
    port: 8125
    protocol: udp
  - hostname: nl03.openstack.org
    port: 8125
    protocol: udp
  - hostname: nl04.openstack.org
    port: 8125
    protocol: udp
  - hostname: zuul01.openstack.org
    port: 8125
    protocol: udp
  - hostname: zm01.openstack.org
    port: 8125
    protocol: udp
  - hostname: zm02.openstack.org
    port: 8125
    protocol: udp
  - hostname: zm03.openstack.org
    port: 8125
    protocol: udp
  - hostname: zm04.openstack.org
    port: 8125
    protocol: udp
  - hostname: zm05.openstack.org
    port: 8125
    protocol: udp
  - hostname: zm06.openstack.org
    port: 8125
    protocol: udp
  - hostname: zm07.openstack.org
    port: 8125
    protocol: udp
  - hostname: zm08.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze01.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze02.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze03.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze04.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze05.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze06.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze07.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze08.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze09.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze10.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze11.openstack.org
    port: 8125
    protocol: udp
  - hostname: ze12.openstack.org
    port: 8125
    protocol: udp
