- name: Get OS specific package names
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.{{ ansible_architecture }}.yaml"
        - "{{ ansible_distribution }}.yaml"
        - "{{ ansible_os_family }}.yaml"
        - "default.yaml"
      paths:
        - vars

- name: Check package names
  fail:
    msg: 'No kerberos client packages defined for this platform'
  when: not kerberos_client_packages

- name: Check realm is set
  fail:
    msg: 'You must set the realm'
  when: realm is not defined

- name: Install configuration file
  template:
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
    src: etc/krb5.conf.j2
  become: yes

- name: Install kerberos client packages
  package:
    name: '{{ kerberos_client_packages }}'
    state: present
  become: yes
