openstack-infra:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack-infra/config
      - openstack-infra/devstack-gate
      - openstack-infra/gerrit
      - openstack-infra/gerrit-trigger-plugin
      - openstack-infra/gerritbot
      - openstack-infra/gerritlib
      - openstack-infra/git-review
      - openstack-infra/jeepyb
      - openstack-infra/jenkins-job-builder
      - openstack-infra/lodgeit
      - openstack-infra/meetbot
      - openstack-infra/nose-html-output
      - openstack-infra/zuul
      - openstack-infra/gearman-plugin
    branches:
      - master

openstack-dev:
    events:
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/ceilometer
      - openstack/cinder
      - openstack/glance
      - openstack/horizon
      - openstack/keystone
      - openstack/nova
      - openstack/oslo-incubator
      - openstack/python-cinderclient
      - openstack/python-glanceclient
      - openstack/python-keystoneclient
      - openstack/python-novaclient
      - openstack/python-openstackclient
      - openstack/python-quantumclient
      - openstack/python-swiftclient
      - openstack/quantum
      - openstack/swift
    branches:
      - master

stackforge-dev:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/libra
      - stackforge/python-libraclient
      - stackforge/python-reddwarfclient
      - stackforge/reddwarf
    branches:
      - master

openstack-metering:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/ceilometer
      - openstack/python-ceilometerclient
    branches:
      - master

openstack-dns:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/moniker
      - stackforge/python-monikerclient
    branches:
      - master

reddwarf:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/reddwarf
      - stackforge/reddwarf-integration
      - stackforge/python-reddwarfclient
    branches:
      - master

tripleo:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/diskimage-builder
    branches:
      - master

heat:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/heat
      - openstack/python-heatclient
    branches:
      - master
