openstack-infra:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack-dev/hacking
      - openstack-dev/pbr
      - openstack-infra/askbot-theme
      - openstack-infra/config
      - openstack-infra/devstack-gate
      - openstack-infra/gear
      - openstack-infra/gearman-plugin
      - openstack-infra/gerrit
      - openstack-infra/gerrit-trigger-plugin
      - openstack-infra/gerritbot
      - openstack-infra/gerritlib
      - openstack-infra/gitdm
      - openstack-infra/git-review
      - openstack-infra/jeepyb
      - openstack-infra/jenkins-job-builder
      - openstack-infra/lodgeit
      - openstack-infra/meetbot
      - openstack-infra/nose-html-output
      - openstack-infra/reviewday
      - openstack-infra/statusbot
      - openstack-infra/zuul
      - openstack/requirements
    branches:
      - master

openstack-dev:
    events:
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/ceilometer
      - openstack/cinder
      - openstack/glance
      - openstack/horizon
      - openstack/keystone
      - openstack/nova
      - openstack/oslo-incubator
      - openstack/oslo.config
      - openstack/python-cinderclient
      - openstack/python-glanceclient
      - openstack/python-keystoneclient
      - openstack/python-novaclient
      - openstack/python-openstackclient
      - openstack/python-quantumclient
      - openstack/python-swiftclient
      - openstack/quantum
      - openstack/swift
      - openstack/tempest
      - openstack-dev/devstack
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
    branches:
      - master

openstack-doc:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/openstack-manuals
      - openstack/api-site
    branches:
      - master

stackforge-dev:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/libra
      - stackforge/python-libraclient
      - stackforge/python-reddwarfclient
      - stackforge/reddwarf
    branches:
      - master

openstack-metering:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/ceilometer
      - openstack/python-ceilometerclient
    branches:
      - master

openstack-dns:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/moniker
      - stackforge/python-monikerclient
    branches:
      - master

reddwarf:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/reddwarf
      - stackforge/reddwarf-integration
      - stackforge/python-reddwarfclient
      - stackforge/database-api
    branches:
      - master

tripleo:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/diskimage-builder
      - stackforge/os-config-applier
      - stackforge/os-refresh-config
      - stackforge/tripleo-image-elements
    branches:
      - master

heat:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/heat
      - openstack/python-heatclient
      - openstack/heat-cfntools
      - openstack/heat-templates
    branches:
      - master

openstack-quantum:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/quantum
      - openstack/python-quantumclient
    branches:
      - master

savanna:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/savanna
      - stackforge/python-savannaclient
    branches:
      - master

openstack-nova:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/nova
      - openstack/python-novaclient
      - openstack/oslo-incubator
      - openstack/oslo.config
    branches:
      - master

openstack-qa:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/tempest
      - openstack-dev/devstack
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
    branches:
      - master

puppet-openstack:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/puppet-cinder
      - stackforge/puppet-glance
      - stackforge/puppet-horizon
      - stackforge/puppet-keystone
      - stackforge/puppet-nova
      - stackforge/puppet-openstack
      - stackforge/puppet-openstack_dev_env
      - stackforge/puppet-quantum
      - stackforge/puppet-swift
    branches:
      - master

chef-openstack:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/cookbook-openstack-block-storage
      - stackforge/cookbook-openstack-image
      - stackforge/cookbook-openstack-dashboard
      - stackforge/cookbook-openstack-identity
      - stackforge/cookbook-openstack-compute
      - stackforge/cookbook-openstack-common
      - stackforge/cookbook-openstack-metering
      - stackforge/cookbook-openstack-network
      - stackforge/cookbook-openstack-object-storage
    branches:
      - master

murano:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/murano-agent
      - stackforge/murano-api
      - stackforge/murano-conductor
      - stackforge/murano-dashboard
      - stackforge/murano-deployment
      - stackforge/murano-docs
      - stackforge/murano-tests
      - stackforge/python-muranoclient
    branches:
      - master

billingstack:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/billingstack
    branches:
      - master

openstack-ironic:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/ironic
      - openstack/python-ironicclient
    branches:
      - master
