openstack-infra:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack-dev/cookiecutter
      - openstack-dev/hacking
      - openstack-dev/pbr
      - openstack-infra/askbot-theme
      - openstack-infra/config
      - openstack-infra/devstack-gate
      - openstack-infra/elastic-recheck
      - openstack-infra/gear
      - openstack-infra/gearman-plugin
      - openstack-infra/gerrit
      - openstack-infra/gerrit-trigger-plugin
      - openstack-infra/gerritbot
      - openstack-infra/gerritlib
      - openstack-infra/gitdm
      - openstack-infra/git-review
      - openstack-infra/jeepyb
      - openstack-infra/jenkins-job-builder
      - openstack-infra/lodgeit
      - openstack-infra/meetbot
      - openstack-infra/nodepool
      - openstack-infra/nose-html-output
      - openstack-infra/odsreg
      - openstack-infra/publications
      - openstack-infra/puppet-apparmor
      - openstack-infra/puppet-dashboard
      - openstack-infra/puppet-vcsrepo
      - openstack-infra/pypi-mirror
      - openstack-infra/releasestatus
      - openstack-infra/reviewday
      - openstack-infra/reviewstats
      - openstack-infra/statusbot
      - openstack-infra/storyboard
      - openstack-infra/zuul
      - openstack/requirements
    branches:
      - master
      - feature/gearman
      - zuul
      - template
      - overview
      - logstash

openstack-doc:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/openstack-manuals
      - openstack/operations-guide
      - openstack/api-site
    branches:
      - master

openstack-metering:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/ceilometer
      - openstack/python-ceilometerclient
      - stackforge/pycadf
    branches:
      - master

openstack-dns:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/designate
      - stackforge/python-designateclient
    branches:
      - master

openstack-trove:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/trove
      - openstack/trove-integration
      - openstack/python-troveclient
      - openstack/database-api
    branches:
      - master

tripleo:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/diskimage-builder
      - openstack/os-collect-config
      - openstack/os-apply-config
      - openstack/os-refresh-config
      - openstack/tripleo-image-elements
      - openstack/tripleo-incubator
      - openstack/tripleo-heat-templates
      - openstack-infra/tripleo-ci
    branches:
      - master

heat:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/heat
      - openstack/python-heatclient
      - openstack/heat-cfntools
      - openstack/heat-templates
      - openstack-dev/heat-cfnclient
    branches:
      - master

openstack-neutron:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/neutron
      - openstack/python-neutronclient
    branches:
      - master

savanna:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/savanna
      - openstack/python-savannaclient
      - openstack/savanna-dashboard
      - openstack/savanna-extra
      - openstack/savanna-image-elements
      - stackforge/puppet-savanna
    branches:
      - master
      - stable/0.1
      - stable/0.2
      - stable/0.3

openstack-nova:
    events:
      - patchset-created
      - x-vrif-minus-2
    projects:
      - openstack/nova
      - openstack/python-novaclient
    branches:
      - master

openstack-cinder:
    events:
      - patchset-created
      - x-vrif-minus-2
    projects:
      - openstack/cinder
      - openstack/python-cinderclient
    branches:
      - master

openstack-qa:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/tempest
      - openstack-dev/devstack
      - openstack-dev/grenade
      - openstack-infra/elastic-recheck
      - openstack-infra/devstack-gate
    branches:
      - master

puppet-openstack:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/puppet-ceilometer
      - stackforge/puppet-cinder
      - stackforge/puppet-glance
      - stackforge/puppet-heat
      - stackforge/puppet-horizon
      - stackforge/puppet-keystone
      - stackforge/puppet-neutron
      - stackforge/puppet-nova
      - stackforge/puppet-openstack
      - stackforge/puppet-openstack_dev_env
      - stackforge/puppet-swift
      - stackforge/puppet-tempest
    branches:
      - master
      - stable/grizzly

openstack-chef:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/cookbook-openstack-block-storage
      - stackforge/cookbook-openstack-image
      - stackforge/cookbook-openstack-dashboard
      - stackforge/cookbook-openstack-identity
      - stackforge/cookbook-openstack-compute
      - stackforge/cookbook-openstack-common
      - stackforge/cookbook-openstack-metering
      - stackforge/cookbook-openstack-network
      - stackforge/cookbook-openstack-object-storage
    branches:
      - master

murano:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/murano-agent
      - stackforge/murano-api
      - stackforge/murano-conductor
      - stackforge/murano-dashboard
      - stackforge/murano-deployment
      - stackforge/murano-docs
      - stackforge/murano-tests
      - stackforge/python-muranoclient
      - stackforge/murano-common
    branches:
      - master

billingstack:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/billingstack
    branches:
      - master

openstack-ironic:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/ironic
      - openstack/python-ironicclient
      - stackforge/pyghmi
    branches:
      - master

openstack-swift:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/swift
      - openstack/python-swiftclient
    branches:
      - master
      - feature/ec

openstack-state-management:
    events:
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/taskflow
    branches:
      - master

openstack-cloudkeep:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/barbican
    branches:
      - master

openstack-glance:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/glance
      - openstack/python-glanceclient
    branches:
      - master

tuskar:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/tuskar
      - stackforge/tuskar-ui
      - stackforge/python-tuskarclient
    branches:
      - master

openstack-marconi:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/marconi
      - openstack/python-marconiclient
    branches:
      - master

stackforge-libra:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/libra
      - stackforge/python-libraclient
    branches:
      - master
