- name: kubectl apply dashboard
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml

- name: copy manifests
  copy:
    src: "{{ role_path }}/files/manifests/"
    dest: "/home/ubuntu/manifests/"


- name: Upload webook kubeconfig file
  template:
    dest: /home/ubuntu/manifests/k8s-keystone-auth.yaml
    src: "{{ role_path }}/templates/k8s-keystone-auth.yaml.j2"

- name: kubectl apply nginx-ingress-controller
  command: kubectl apply -f /home/ubuntu/manifests/nginx-ingress-controller.yaml

- name: kubectl apply admin-user for dashboard
  command: kubectl apply -f /home/ubuntu/manifests/admin-user.yaml

- name: include helm
  include: helm.yaml
  when: helm_include

- name: copy syncconfig.yaml
  become: true
  copy:
   src: "{{ role_path }}/files/syncconfig.yaml"
   dest: "/etc/kubernetes/syncconfig.yaml"

- name: kubectl apply k8s-keystone-auth
  command: kubectl apply -f /home/ubuntu/manifests/k8s-keystone-auth.yaml
