- fail:
    msg: "Unsupported puppet version '{{ puppet_install_version }}' on this platform"
  when: puppet_install_version not in [3, 4]

- name: Install puppet 3 packages
  when: puppet_install_version == 3
  become: true
  block:
    # Note https doesn't work here due to certificate issues and
    # python versions and SNI etc; not worth the effort of workarounds
    # at this point.
    - name: Install puppetlabs repo
      apt:
        deb: http://apt.puppetlabs.com/puppetlabs-release-trusty.deb

    - name: Install puppet packages
      package:
        state: present
        name:
          - puppet
          - ruby

- name: Install puppet 4 packages
  when: puppet_install_version == 4
  become: true
  block:
    - name: Install puppetlabs repo
      apt:
        deb: http://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb

    - name: Install puppet packages
      apt:
        name:
          - puppet-agent
          - ruby
        update_cache: yes

- name: Stop and disable puppet service
  service:
    name: puppet
    state: stopped
    enabled: no
  become: yes
