openstack-infra:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/openstack-ci-puppet
      - openstack-ci/git-review
      - openstack-ci/zuul
    branches:
      - master

openstack-dev:
    events:
      - change-merged
      - x-vrif-minus-2
    projects:
      - openstack/cinder
      - openstack/glance
      - openstack/horizon
      - openstack/keystone
      - openstack/nova
      - openstack/openstack-common
      - openstack/python-cinderclient
      - openstack/python-glanceclient
      - openstack/python-keystoneclient
      - openstack/python-novaclient
      - openstack/python-openstackclient
      - openstack/python-quantumclient
      - openstack/python-swiftclient
      - openstack/quantum
      - openstack/swift
    branches:
      - master

stackforge-dev:
    events:
      - patchset-created
      - change-merged
      - x-vrif-minus-2
    projects:
      - stackforge/ceilometer
      - heat-api/heat
    branches:
      - master
