- job:
    name: 'gate-ceilometer-python26-essex'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - python26-essex

    publishers:
      - console-log

    # >= precise does not have python2.6
    node: oneiric
  

- job:
    name: 'gate-ceilometer-python27-essex'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - python27-essex

    publishers:
      - console-log

    node: oneiric
