- job-template:
    name: 'gate-{name}-chef-unit'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - chef-bundler-prep
      - chef-berkshelf-prep
      - chef-cookbook-chefspec

    publishers:
      - console-log

- job-template:
    name: 'gate-{name}-chef-lint'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - chef-bundler-prep
      - chef-berkshelf-prep
      - chef-cookbook-foodcritic

    publishers:
      - console-log

- job-template:
    name: 'gate-{name}-chef-style'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - chef-bundler-prep
      - chef-berkshelf-prep
      - chef-cookbook-rubocop

    publishers:
      - console-log

- job:
    name: gate-openstack-chef-repo
    node: bare-precise

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          mkdir -p .cookbooks .bundle
          ruby1.9.1 /usr/bin/bundle config --global jobs $(nproc)
          ruby1.9.1 /usr/bin/bundle install --path=.bundle
          # Validates cookbooks
          ruby1.9.1 /usr/bin/bundle exec berks install --path=.cookbooks
          # Validates roles
          ruby1.9.1 /usr/bin/bundle exec spiceweasel infrastructure.yml --debug

    publishers:
      - console-log
