- job-template:
    name: 'periodic-tempest-dsvm-full{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 95
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=90
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-stable-maint@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-postgres-full{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 95
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=90
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_POSTGRES=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-stable-maint@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-neutron{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 95
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=90
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_SMOKE_SERIAL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-stable-maint@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-all{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 185
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_ALL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-stress{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 185
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_STRESS=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-neutron-pg{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 125
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=120
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_POSTGRES=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_SMOKE_SERIAL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-large-ops{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 65
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=60
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_LARGE_OPS=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-neutron-large-ops{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 65
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=60
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_LARGE_OPS=1
          export DEVSTACK_GATE_NEUTRON=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-all{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 185
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_ALL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-coverage{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 185
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_COVERAGE=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-stress{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 185
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_STRESS=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-savanna-full{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 95
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=90
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export DEVSTACK_GATE_SAVANNA=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-stable-maint@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-savanna-postgres-full{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 95
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=90
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_POSTGRES=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export DEVSTACK_GATE_SAVANNA=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-stable-maint@lists.openstack.org


- job-template:
    name: 'periodic-tempest-dsvm-savanna-neutron{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 95
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=90
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_SMOKE_SERIAL=1
          export DEVSTACK_GATE_SAVANNA=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-stable-maint@lists.openstack.org


- job-group:
    name: devstack-periodic-jobs
    jobs:
      - 'periodic-tempest-dsvm-full{branch-designator}'
      - 'periodic-tempest-dsvm-postgres-full{branch-designator}'
      - 'periodic-tempest-dsvm-neutron{branch-designator}'
      - 'periodic-tempest-dsvm-all{branch-designator}'
      - 'periodic-tempest-dsvm-coverage{branch-designator}'
      - 'periodic-tempest-dsvm-stress{branch-designator}'
      - 'periodic-tempest-dsvm-neutron-pg{branch-designator}'
      - 'periodic-tempest-dsvm-large-ops{branch-designator}'
      - 'periodic-tempest-dsvm-neutron-large-ops{branch-designator}'
      - 'periodic-tempest-dsvm-all{branch-designator}'
      - 'periodic-tempest-dsvm-coverage{branch-designator}'
      - 'periodic-tempest-dsvm-stress{branch-designator}'
      - 'periodic-tempest-dsvm-savanna-full{branch-designator}'
      - 'periodic-tempest-dsvm-savanna-postgres-full{branch-designator}'
      - 'periodic-tempest-dsvm-savanna-neutron{branch-designator}'
