- job-template:
    name: '{pipeline}-tempest-devstack-vm-full'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 90
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job:
    name: gate-tempest-devstack-vm-iad-trial
    node: devstack-precise-iad

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export ZUUL_BRANCH=master
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic


- job:
    name: gate-tempest-devstack-vm-dfw-trial
    node: devstack-precise-dfw

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export ZUUL_BRANCH=master
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic


- job:
    name: gate-tempest-devstack-vm-ord-trial
    node: devstack-precise-ord

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export ZUUL_BRANCH=master
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic


- job:
    name: gate-tempest-devstack-vm-heat-slow
    node: devstack-precise

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_HEAT_SLOW=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-tempest-devstack-vm-neutron'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_SMOKE_SERIAL=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-tempest-devstack-vm-neutron-pg'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_POSTGRES=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_SMOKE_SERIAL=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-tempest-devstack-vm-neutron-isolated'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST_ALLOW_TENANT_ISOLATION=1
          export DEVSTACK_GATE_SMOKE_SERIAL=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-tempest-devstack-vm-neutron-pg-isolated'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_POSTGRES=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST_ALLOW_TENANT_ISOLATION=1
          export DEVSTACK_GATE_SMOKE_SERIAL=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-tempest-devstack-vm-neutron-full'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_TESTR_FULL=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST_ALLOW_TENANT_ISOLATION=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-devstack-vm-cells'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_CELLS=1
          export DEVSTACK_GATE_EXERCISES=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-tempest-devstack-vm-cells'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_CELLS=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-tempest-devstack-vm-cells-full'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export DEVSTACK_GATE_CELLS=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-tempest-devstack-vm-large-ops'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_LARGE_OPS=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log

- job-template:
    name: '{pipeline}-tempest-devstack-vm-neutron-large-ops'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_LARGE_OPS=1
          export DEVSTACK_GATE_NEUTRON=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job:
    name: periodic-tempest-devstack-vm-all
    node: devstack-precise

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_ALL=1
          export ZUUL_BRANCH=master
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job:
    name: periodic-tempest-devstack-vm-coverage
    node: devstack-precise

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_COVERAGE=1
          export ZUUL_BRANCH=master
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job:
    name: periodic-tempest-devstack-vm-stress
    node: devstack-precise

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_STRESS=1
          export ZUUL_BRANCH=master
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job:
    name: gate-tempest-devstack-vm-postgres-zeromq-full
    node: devstack-precise

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export DEVSTACK_GATE_POSTGRES=1
          export DEVSTACK_GATE_ZEROMQ=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-tempest-devstack-vm-postgres'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_POSTGRES=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-tempest-devstack-vm-postgres-full'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 90
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export DEVSTACK_GATE_POSTGRES=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: '{pipeline}-grenade-devstack-vm'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_GRENADE=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job:
    name: gate-grenade-devstack-vm-stable
    node: devstack-precise

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_GRENADE=1
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-group:
    name: devstack-jobs
    jobs:
      - '{pipeline}-tempest-devstack-vm-full'
      - '{pipeline}-tempest-devstack-vm-neutron'
      - '{pipeline}-tempest-devstack-vm-neutron-pg'
      - '{pipeline}-tempest-devstack-vm-neutron-isolated'
      - '{pipeline}-tempest-devstack-vm-neutron-pg-isolated'
      - '{pipeline}-tempest-devstack-vm-neutron-full'
      - '{pipeline}-devstack-vm-cells'
      - '{pipeline}-tempest-devstack-vm-cells'
      - '{pipeline}-tempest-devstack-vm-cells-full'
      - '{pipeline}-tempest-devstack-vm-large-ops'
      - '{pipeline}-tempest-devstack-vm-neutron-large-ops'
      - '{pipeline}-tempest-devstack-vm-postgres'
      - '{pipeline}-tempest-devstack-vm-postgres-full'
      - '{pipeline}-grenade-devstack-vm'
