- job-template:
    name: 'periodic-tempest-devstack-vm-full-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 90
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-stable-maint@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-postgres-full-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 90
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_POSTGRES=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-stable-maint@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-neutron-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 90
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_SMOKE_SERIAL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-stable-maint@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-all-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_ALL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-coverage-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_COVERAGE=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-stress-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_STRESS=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-neutron-pg-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_POSTGRES=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_SMOKE_SERIAL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-large-ops-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_LARGE_OPS=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-neutron-large-ops-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_LARGE_OPS=1
          export DEVSTACK_GATE_NEUTRON=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-all-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_ALL=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-coverage-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_COVERAGE=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-template:
    name: 'periodic-tempest-devstack-vm-stress-{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 180
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_STRESS=1
          export ZUUL_BRANCH={branch-override}
          unset ZUUL_PROJECT
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org


- job-group:
    name: devstack-periodic-jobs
    jobs:
      - 'periodic-tempest-devstack-vm-full-{branch-designator}'
      - 'periodic-tempest-devstack-vm-postgres-full-{branch-designator}'
      - 'periodic-tempest-devstack-vm-neutron-{branch-designator}'
      - 'periodic-tempest-devstack-vm-all-{branch-designator}'
      - 'periodic-tempest-devstack-vm-coverage-{branch-designator}'
      - 'periodic-tempest-devstack-vm-stress-{branch-designator}'
      - 'periodic-tempest-devstack-vm-neutron-pg-{branch-designator}'
      - 'periodic-tempest-devstack-vm-large-ops-{branch-designator}'
      - 'periodic-tempest-devstack-vm-neutron-large-ops-{branch-designator}'
      - 'periodic-tempest-devstack-vm-all-{branch-designator}'
      - 'periodic-tempest-devstack-vm-coverage-{branch-designator}'
      - 'periodic-tempest-devstack-vm-stress-{branch-designator}'
