- job:
    name: elastic-recheck-docs
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - docs

    publishers:
      - ftp:
          site: docs.openstack.org
          source: 'doc/build/html/**'
          target: 'infra/elastic-recheck/'
          remove-prefix: 'doc/build/html'
          excludes: ''
      - console-log
