- job:
    name: gate-gearman-plugin-build
    project-type: maven
    node: precise && !jclouds

    triggers:
      - zuul

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.jenkins-ci.plugins
        artifact-id: gearman-plugin
      root-pom: pom.xml
      goals: 'clean package'

    publishers:
      - console-log
