
- job-template:
    name: 'periodic-gerrit-plugin-{name}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 30
          fail: true
      - timestamps

    builders:
      - revoke-sudo
      - shell: |
          #!/bin/bash -xe
          rm -rf gerrit
          git clone -b {gerrit-branch} {gerrit-project}
          git clone -b {plugin-branch} {plugin-project} gerrit/plugins/{plugin-name}
          cd gerrit/plugins/{plugin-name}
          /usr/local/jenkins/slave_scripts/version-properties.sh
      - inject:
          properties-file: gerrit/plugins/{plugin-name}/version.properties
      - install-buck
      - shell: |
          #!/bin/bash -xe
          export PATH=`pwd`/buck/bin:$PATH
          cd gerrit
          buck clean
          buck build plugins/{plugin-name}:{plugin-name}
          cp gerrit/buck-out/gen/plugins/{plugin-name}/{plugin-name}.jar gerrit/buck-out/gen/plugins/{plugin-name}/{plugin-name}-$PROJECT_VER.jar

    publishers:
      - war:
          site: '{tarball-site}'
          warfile: 'gerrit/buck-out/gen/plugins/{plugin-name}/{plugin-name}-${{PROJECT_VER}}.jar'
          target: 'tarballs/ci/{name}'
      - console-log

- job-group:
    name: gerrit-plugin-jobs
    jobs:
      - 'periodic-gerrit-plugin-{name}'
