- job:
    name: check-gerrit-unittests
    project-type: maven
    node: precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true

    triggers:
      - zuul

    prebuilders:
      - gerrit-git-prep
      - gerrit-preclean

    maven:
      maven-name: Maven3
      root-module:
        group-id: com.google.gerrit
        artifact-id: gerrit-parent
      goals: 'clean package -Dgerrit.include-documentation=1 -X'

    postbuilders:
      - gerrit-postrun

    publishers:
      - war:
          site: 'tarballs.openstack.org'
          warfile: 'gerrit-war/target/gerrit*.war'
          target: 'tarballs/ci/test/'
      - console-log


- job:
    name: gate-gerrit-unittests
    project-type: maven
    node: precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true

    triggers:
      - zuul

    prebuilders:
      - gerrit-git-prep
      - gerrit-preclean

    maven:
      maven-name: Maven3
      root-module:
        group-id: com.google.gerrit
        artifact-id: gerrit-parent
      goals: 'clean package -Dgerrit.include-documentation=1 -X'

    postbuilders:
      - gerrit-postrun

    publishers:
      - console-log

- job:
    name: gerrit-package
    project-type: maven
    node: precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true

    triggers:
      - zuul-post

    prebuilders:
      - gerrit-git-prep
      - gerrit-preclean

    maven:
      maven-name: Maven3
      root-module:
        group-id: com.google.gerrit
        artifact-id: gerrit-parent
      goals: 'clean package -Dgerrit.include-documentation=1 -X'

    postbuilders:
      - gerrit-postrun

    publishers:
      - war:
          site: 'tarballs.openstack.org'
          warfile: 'gerrit-war/target/gerrit*.war'
          target: 'tarballs/ci/'
      - console-log-post
