
- job-template:
    name: 'periodic-gerrit-plugin-{name}'
    node: '{node}'

    wrappers:
      - build-timeout:
          timeout: 30
      - timestamps

    builders:
      - revoke-sudo
      - install-buck
      - shell: |
          #!/bin/bash -xe
          export PATH=`pwd`/buck/bin:$PATH
          rm -rf gerrit
          git clone -b {gerrit-branch} {gerrit-project}
          git clone -b {plugin-branch} {plugin-project} gerrit/plugins/{plugin-name}
          cd gerrit/plugins/{plugin-name}
          /usr/local/jenkins/slave_scripts/version-properties.sh
          source version.properties
          cd $WORKSPACE/gerrit
          buck clean
          buck build plugins/{plugin-name}:{plugin-name}
          cp ./buck-out/gen/plugins/{plugin-name}/{plugin-name}.jar ./buck-out/gen/plugins/{plugin-name}/{plugin-name}-$PROJECT_VER.jar

    publishers:
      - war:
          site: '{tarball-site}'
          warfile: 'gerrit/buck-out/gen/plugins/{plugin-name}/{plugin-name}-*.jar'
          target: 'tarballs/ci/gerrit/plugins/{plugin-name}'
      - console-log

- job-group:
    name: gerrit-plugin-jobs
    jobs:
      - 'periodic-gerrit-plugin-{name}'
