- job:
    name: check-gerrit-unittests
    project-type: maven
    node: bare-precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    prebuilders:
      - gerrit-git-prep
      - gerrit-preclean

    maven:
      maven-name: Maven3
      root-module:
        group-id: com.google.gerrit
        artifact-id: gerrit-parent
      goals: 'clean package -Dgerrit.include-documentation=1 -X -B'

    postbuilders:
      - gerrit-postrun

    publishers:
      - war:
          site: 'tarballs.openstack.org'
          warfile: 'gerrit-war/target/gerrit*.war'
          target: 'tarballs/ci/test/'
      - console-log


- job:
    name: gate-gerrit-unittests
    project-type: maven
    node: bare-precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    prebuilders:
      - gerrit-git-prep
      - gerrit-preclean

    maven:
      maven-name: Maven3
      root-module:
        group-id: com.google.gerrit
        artifact-id: gerrit-parent
      goals: 'clean package -Dgerrit.include-documentation=1 -X -B'

    postbuilders:
      - gerrit-postrun

    publishers:
      - console-log

- job:
    name: gerrit-package
    project-type: maven
    node: bare-precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    prebuilders:
      - gerrit-git-prep
      - gerrit-preclean

    maven:
      maven-name: Maven3
      root-module:
        group-id: com.google.gerrit
        artifact-id: gerrit-parent
      goals: 'clean package -Dgerrit.include-documentation=1 -X -B'

    postbuilders:
      - gerrit-postrun

    publishers:
      - war:
          site: 'tarballs.openstack.org'
          warfile: 'gerrit-war/target/gerrit*.war'
          target: 'tarballs/ci/gerrit'
      - console-log

- job:
    name: check-gerrit-buck
    node: bare-precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    builders:
      - shell: |
          #!/bin/bash -xe
          mkdir -p gerrit
          cd gerrit
          /usr/local/jenkins/slave_scripts/gerrit-git-prep.sh https://review.openstack.org http://zuul.openstack.org git://git.openstack.org
      - shell: |
          #!/bin/bash -xe
          cd gerrit
          /usr/local/jenkins/slave_scripts/maven-properties.sh
      - inject:
          properties-file: gerrit/maven.properties
      - install-buck
      - shell: |
          #!/bin/bash -xe
          export PATH=`pwd`/buck/bin:$PATH
          cd gerrit
          buck clean
          buck test --all --exclude slow
          buck build release
      - shell: "cp gerrit/buck-out/gen/release.war gerrit/buck-out/gen/gerrit-$PROJECT_VER.war"

    publishers:
      - war:
          site: 'tarballs.openstack.org'
          warfile: 'gerrit/buck-out/gen/gerrit-${PROJECT_VER}.war'
          target: 'tarballs/ci/test'
      - console-log

- job:
    name: gate-gerrit-buck
    node: bare-precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    builders:
      - shell: |
          #!/bin/bash -xe
          mkdir -p gerrit
          cd gerrit
          /usr/local/jenkins/slave_scripts/gerrit-git-prep.sh https://review.openstack.org http://zuul.openstack.org git://git.openstack.org
      - shell: |
          #!/bin/bash -xe
          cd gerrit
          /usr/local/jenkins/slave_scripts/maven-properties.sh
      - inject:
          properties-file: gerrit/maven.properties
      - install-buck
      - shell: |
          #!/bin/bash -xe
          export PATH=`pwd`/buck/bin:$PATH
          cd gerrit
          buck clean
          buck test --all --exclude slow
          buck build release
      - shell: "cp gerrit/buck-out/gen/release.war gerrit/buck-out/gen/gerrit-$PROJECT_VER.war"

    publishers:
      - console-log

- job:
    name: gerrit-package-buck
    node: bare-precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    builders:
      - shell: |
          #!/bin/bash -xe
          mkdir -p gerrit
          cd gerrit
          /usr/local/jenkins/slave_scripts/gerrit-git-prep.sh https://review.openstack.org http://zuul.openstack.org git://git.openstack.org
      - shell: |
          #!/bin/bash -xe
          cd gerrit
          /usr/local/jenkins/slave_scripts/maven-properties.sh
      - inject:
          properties-file: gerrit/maven.properties
      - install-buck
      - shell: |
          #!/bin/bash -xe
          export PATH=`pwd`/buck/bin:$PATH
          cd gerrit
          buck clean
          buck test --all --exclude slow
          buck build release
      - shell: "cp gerrit/buck-out/gen/release.war gerrit/buck-out/gen/gerrit-$PROJECT_VER.war"

    publishers:
      - war:
          site: 'tarballs.openstack.org'
          warfile: 'gerrit/buck-out/gen/gerrit-${PROJECT_VER}.war'
          target: 'tarballs/ci/gerrit'
      - console-log
