- job:
    name: gate-groups-unittests
    node: '{node}'

    builders:
        - gerrit-git-prep
        - shell: |
            #!/bin/bash -xe
            # fetch drush
            mkdir drush
            curl -L https://github.com/drush-ops/drush/archive/6.0.0.tar.gz | tar -xz -C drush --strip 1
            # build distribution
            ./drush/drush make build-groups.make dist
    publishers:
        - console-log
        - coverage-log
        - scp:
            site: 'static.openstack.org'
            files:
                - target: 'logs/$LOG_PATH'
                  source: './reports/**'
                  keep-hierarchy: true
                  copy-after-failure: true

- job-template:
    name: 'groups-release-{branch-designator}'
    node: '{node}'

    builders:
        - gerrit-git-prep
        - shell: |
            #!/bin/bash -xe
            /usr/local/jenkins/slave_scripts/maven-properties.sh
        - inject:
            properties-file: maven.properties
        - shell: |
            #!/bin/bash -xe
            # fetch drush
            mkdir drush
            curl -L https://github.com/drush-ops/drush/archive/6.0.0.tar.gz | tar -xz -C drush --strip 1
            # build distribution
            ./drush/drush make build-groups.make dist
            # Clean/create a tarball directory
            rm -rf tarballs
            mkdir -p tarballs
            # Create an archive tarball.
            tar -czf groups-$PROJECT_VER.tar.gz dist/
            cp groups-$PROJECT_VER.tar.gz tarballs/groups-latest.tar.gz
            mv groups-$PROJECT_VER.tar.gz tarballs/
    publishers:
        - console-log
        - coverage-log
        - scp:
            site: 'static.openstack.org'
            files:
                - target: 'logs/$LOG_PATH'
                  source: './reports/**'
                  keep-hierarchy: true
                  copy-after-failure: true
                - target: 'tarballs/groups/'
                  source: 'tarballs/*.tar.gz'
                  keep-hierarchy: false
                  copy-after-failure: false
