- job-template:
    name: gate-hacking-integration-{target-project}
    node: bare-precise

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          source /usr/local/jenkins/slave_scripts/select-mirror.sh openstack-dev hacking
          tox -e integration {target-org} {target-project}

    publishers:
      - console-log
