- job:
    name: gate-horizon-selenium
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - selenium

    publishers:
      - console-log

- job:
    name: gate-horizon-python27-django14
    node: 'bare-precise || bare-trusty'

    wrappers:
      - build-timeout:
          timeout: 40
      - timestamps

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: '/usr/local/jenkins/slave_scripts/run-unittests.sh 27dj14'
      - assert-no-extra-files

    publishers:
      - test-results
      - console-log

- job:
    name: gate-horizon-jshint
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - tox:
          envlist: jshint

    publishers:
      - console-log

- job:
    name: gate-horizon-dsvm-integration
    node: 'devstack-precise || devstack-trusty'

    wrappers:
      - build-timeout:
          timeout: 95
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=90
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          export DEVSTACK_GATE_INSTALL_TESTONLY=1
          export BRANCH_OVERRIDE={branch-override}
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
               export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function post_test_hook {{
              cd /opt/stack/new/horizon
              tox -e py27integration
          }}
          export -f post_test_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - test-results
      - devstack-logs
      - console-log
