- job:
    name: config-compare-xml
    node: bare-precise

    builders:
      - gerrit-git-prep
      - shell: "./tools/run-compare-xml.sh openstack-infra config"

    publishers:
      - console-log


- job:
    name: gate-config-layout
    node: bare-precise

    builders:
      - gerrit-git-prep
      - shell: |
          source /usr/local/jenkins/slave_scripts/select-mirror.sh openstack-infra config
          ./tools/run-layout.sh openstack-infra config

    publishers:
      - console-log


# This is a non-standard docs job because it uses SCP instead of FTP
- job:
    name: ci-docs
    node: bare-precise

    builders:
      - gerrit-git-prep
      - docs:
          github-org: openstack-infra
          project: config

    publishers:
      - scp:
          site: '173.203.107.207'
          files:
            - target: 'ci'
              source: 'doc/build/html/**/*'
              keep-hierarchy: true
      - console-log


- job:
    name: gate-ci-docs
    node: bare-precise

    builders:
      - gerrit-git-prep
      - docs:
          github-org: openstack-infra
          project: config

    publishers:
      - console-log
      - upload-sphinx-draft


- job:
    name: check-projects-yaml-alphabetized
    node: bare-precise

    builders:
      - gerrit-git-prep
      - shell: |
          /usr/local/jenkins/slave_scripts/check_projects_yaml_alphabetized.sh

    publishers:
      - console-log
