- job:
    name: config-compare-xml
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: ./tools/run-compare-xml.sh

    publishers:
      - console-log


- job:
    name: gate-config-irc-access
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - tox:
          envlist: 'irc'

    publishers:
      - console-log


- job:
    name: gate-config-layout
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          ./tools/run-layout.sh

    publishers:
      - console-log


# This is a non-standard docs job because it uses SCP instead of FTP
- job:
    name: ci-docs
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - docs

    publishers:
      - scp:
          site: '173.203.107.207'
          files:
            - target: 'ci'
              source: 'doc/build/html/**/*'
              keep-hierarchy: true
      - console-log


- job:
    name: gate-ci-docs
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - docs

    publishers:
      - console-log
      - upload-sphinx-draft


- job:
    name: check-projects-yaml-alphabetized
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - tox:
          envlist: projects_alphabetized

    publishers:
      - console-log


- job:
    name: check-projects-yaml-upstream
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - tox:
          envlist: upstream

    publishers:
      - console-log
