- job-template:
    name: '{name}-infra-docs'
    node: '{node}'

    builders:
        - revoke-sudo
        - gerrit-git-prep
        - docs

    publishers:
        - console-log
        - ftp:
            site: '{doc-publisher-site}'
            source: 'doc/build/html/**'
            target: 'infra/{doc-publisher-folder}'
            remove-prefix: 'doc/build/html'
            excludes: ''

- job-group:
    name: infra-publish-jobs
    jobs:
        - 'gate-{name}-docs'
        - '{name}-infra-docs'
