- job:
    name: config-compare-xml
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: ./tools/run-compare-xml.sh
      - zuul_swift_upload_console_log

    publishers:
      - console-log


- job:
    name: gate-config-irc-access
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - tox:
          envlist: 'irc'
      - zuul_swift_upload_console_log

    publishers:
      - console-log


- job:
    name: gate-config-layout
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          ./tools/run-layout.sh
      - zuul_swift_upload_console_log

    publishers:
      - console-log


# This is a non-standard docs job because it uses SCP instead of FTP
- job:
    name: ci-docs
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - docs
      - zuul_swift_upload_console_log
      # TODO(jhesketh): Add job for uploading built docs

    publishers:
      - scp:
          site: '173.203.107.207'
          files:
            - target: 'ci'
              source: 'doc/build/html/**/*'
              keep-hierarchy: true
      - console-log


- job:
    name: gate-ci-docs
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - docs
      - zuul_swift_upload_console_log
      # TODO(jhesketh): Add job for uploading sphinx docs

    publishers:
      - console-log
      - upload-sphinx-draft


- job:
    name: gate-config-projects-yaml
    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - tox:
          envlist: projects
      - zuul_swift_upload_console_log

    publishers:
      - console-log

- job-template:
    name: 'gate-infra-puppet-apply-{ostype}'
    node: 'bare-{ostype}'

    builders:
      - shell: |
          #!/bin/bash -xe
          /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git git://git.openstack.org openstack-infra/config
          cd openstack-infra/config
          ./tools/apply-test.sh
      - zuul_swift_upload_console_log

    publishers:
      - console-log
