- job:
    name: 'gate-ironic-python-agent-buildimage-coreos'
    node: 'bare-trusty'

    builders:
      - link-logs
      - net-info
      - gerrit-git-prep
      - shell: |
          imagebuild/coreos/full_trusty_build.sh

    publishers:
      - console-log

- job:
    name: 'ironic-python-agent-buildimage-coreos'
    node: 'bare-trusty'

    builders:
      - link-logs
      - net-info
      - gerrit-git-prep
      - shell: |
          imagebuild/coreos/full_trusty_build.sh


    publishers:
      - scp:
          site: 'tarballs.openstack.org'
          files:
            - source: 'imagebuild/coreos/UPLOAD/coreos_production_pxe.vmlinuz'
              target: 'tarballs/ironic-python-agent/coreos/files'
              keep-hierarchy: false
              copy-after-failure: false
            - source: 'imagebuild/coreos/UPLOAD/coreos_production_pxe_image-oem.cpio.gz'
              target: 'tarballs/ironic-python-agent/coreos/files'
              keep-hierarchy: false
              copy-after-failure: false
            - source: 'ipa-coreos.tar.gz'
              target: 'tarballs/ironic-python-agent/coreos'
              keep-hierarchy: false
              copy-after-failure: false
      - console-log
