- job-template:
    name: 'gate-{name}-build'
    project-type: maven
    node: precise

    prebuilders:
      - gerrit-git-prep

    wrappers:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/maven-properties.sh
      - inject:
          properties-file: maven.properties

    maven:
      maven-name: Maven3
      root-module:
        group-id: '{maven-group-id}'
        artifact-id: '{name}'
      root-pom: pom.xml
      goals: 'clean package -Dproject-version=${{PROJECT_VER}}'

    publishers:
      - console-log

- job-template:
    name: '{name}-hpi-artifact'
    project-type: maven
    node: precise

    prebuilders:
      - gerrit-git-prep

    wrappers:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/maven-properties.sh
      - inject:
          properties-file: maven.properties

    maven:
      maven-name: Maven3
      root-module:
        group-id: '{maven-group-id}'
        artifact-id: '{name}'
      root-pom: pom.xml
      goals: 'clean package -Dmaven.test.skip=true -Dproject-version=${{PROJECT_VER}}'

    publishers:
      - war:
          site: 'tarballs.openstack.org'
          warfile: 'target/{name}.hpi'
          target: 'tarballs/ci/{name}/{name}-${{PROJECT_VER}}.hpi'
      - console-log-post

- job-template:
    name: '{name}-jenkinsci-upload'
    node: pypi

    builders:
      - shell: |
          #!/bin/bash -xe
          TAG=`echo $ZUUL_REF | sed 's/^refs.tags.//'`
          FILENAME="{name}-$TAG.hpi"

          # copy plugin plugin artifacts from tarballs to local workspace
          rm -rf *.hpi
          curl -o $FILENAME http://{tarball-site}/ci/{name}/$FILENAME

          # deploy plugin artifacts from workspace to repo.jenkins-ci.org
          JENKINSCI_REPO="http://repo.jenkins-ci.org/list/releases/org/jenkins-ci/plugins"
          JENKINSCI_REPO_CREDS="/home/jenkins/.jenkinsci-curl"
          /usr/local/jenkins/slave_scripts/maven-upload.sh {name} $JENKINSCI_REPO $JENKINSCI_REPO_CREDS

    publishers:
      - console-log-post

- job-group:
    name: jenkins-plugin-jobs
    jobs:
      - 'gate-{name}-build'
      - '{name}-hpi-artifact'
      - '{name}-jenkinsci-upload'
