# This is a non-standard docs job because it uses SCP instead of FTP
- job:
    name: jenkins-job-builder-docs
    node: bare-precise

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - docs:
          github-org: openstack-infra
          project: jenkins-job-builder

    publishers:
      - scp:
          site: '173.203.107.207'
          files:
            - target: 'ci/jenkins-job-builder'
              source: 'doc/build/html/**/*'
              keep-hierarchy: true
      - console-log

- job:
    name: jenkins-job-builder-compare-xml
    node: bare-precise

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          source /usr/local/jenkins/slave_scripts/select-mirror.sh openstack-infra jenkins-job-builder
          ./tools/run-compare-xml.sh

    publishers:
      - console-log
