- builder:
    name: gerrit-git-prep
    builders:
      - shell: "/usr/local/jenkins/slave_scripts/gerrit-git-prep.sh review.openstack.org"

- builder:
    name: coverage
    builders:
      - shell: "/usr/local/jenkins/slave_scripts/run-cover.sh"

- builder:
    name: docs
    builders:
      - shell: "/usr/local/jenkins/slave_scripts/run-docs.sh"

- builder:
    name: maven-test
    builders:
      - shell: "mvn test"

- builder:
    name: maven-package
    builders:
      - shell: "mvn package"

- builder:
    name: markdown-docbook
    builders:
      - shell: "/usr/local/jenkins/slave_scripts/markdown-docbook.sh {filename}"

- builder:
    name: gerrit-package
    builders:
      - shell: "/usr/local/jenkins/slave_scripts/package-gerrit.sh"

- builder:
    name: gerrit-preclean
    builders:
      - shell: |
          #!/bin/bash -xe
          rm -fr ~/.m2
          rm -fr ~/.java
          ./tools/version.sh --release

- builder:
    name: gerrit-postrun
    builders:
      - shell: "./tools/version.sh --reset"

- builder:
    name: pep8
    builders:
      - shell: "set -o pipefail ; tox -v -epep8 | tee pep8.txt ; set +o pipefail"

- builder:
    name: pylint
    builders:
      - shell: "set -o pipefail ; tox -v -epylint | tee pylint.txt ; set +o pipefail"

- builder:
    name: pyflakes
    builders:
      - shell: "tox -v -epyflakes"

- builder:
    name: puppet-syntax
    builders:
      - shell: |
          find . -iname *.pp | xargs puppet parser validate --modulepath=`pwd`/modules
          for f in `find . -iname *.erb` ; do
            erb -x -T '-' $f | ruby -c
          done

- builder:
    name: selenium
    builders:
      - shell: "/usr/local/jenkins/slave_scripts/run-selenium.sh"

- builder:
    name: python26
    builders:
      - shell: "/usr/local/jenkins/slave_scripts/run-tox.sh 26"
      - something:
          arg: value

- builder:
    name: python27
    builders:
      - shell: "/usr/local/jenkins/slave_scripts/run-tox.sh 27"

- builder:
    name: tarball
    builders:
      - shell: "/usr/local/jenkins/slave_scripts/create-tarball.sh {project}"

- builder:
    name: devstack-checkout
    builders:
      - shell: |
          #!/bin/bash -xe
          if [[ ! -e devstack-gate ]]; then
              git clone https://review.openstack.org/p/openstack-ci/devstack-gate
          else
              cd devstack-gate
              git remote update
              git reset --hard
              git clean -x -f
              git checkout master
              git reset --hard remotes/origin/master
              git clean -x -f
              cd ..
          fi


# ======================================================================

- publisher:
    name: tarball
    publishers:
      - archive:
          artifacts: 'dist/*.tar.gz'
      - scp:
          site: '{site}'
          files:
            - target: 'tarballs/{project}/'
              source: 'dist/*.tar.gz'

- publisher:
    name: war
    publishers:
      - archive:
          artifacts: '{warfile}'
      - scp:
          site: '{site}'
          files:
            - target: '{target}'
              source: '{warfile}'

- publisher:
    name: pep8
    publishers:
      - violations:
          pep8:
            min: 0
            max: 1
            unstable: 1
            pattern: '**/pep8.txt'

- publisher:
    name: pylint
    publishers:
      - violations:
          pylint:
            min: 0
            max: 1
            unstable: 1
            pattern: '**/pylint.txt'

- publisher:
    name: console-log
    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              copy-console: true
              copy-after-failure: true

- publisher:
    name: console-log-post
    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$ZUUL_SHORT_NEWREV/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              copy-console: true
              copy-after-failure: true

- publisher:
    name: console-log-periodic
    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/periodic/$JOB_NAME/$BUILD_NUMBER'
              copy-console: true
              copy-after-failure: true
