- job:
    name: gate-magnetodb-devstack-dsvm
    node: 'devstack-precise || devstack-trusty'

    wrappers:
      - build-timeout:
          timeout: 65
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=60
          export ENABLED_SERVICES=magnetodb,tempest
          export PROJECTS="stackforge/magnetodb $PROJECTS"

          function pre_test_hook {
              cd /opt/stack/new/magnetodb/functionaltests
              ./pre_test_hook.sh
          }
          export -f pre_test_hook

          function post_test_hook {
              cd /opt/stack/new/magnetodb/functionaltests
              ./post_test_hook.sh
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: 'gate-magnetodb-cassandra-tox'

    wrappers:
      - build-timeout:
          timeout: 40
      - timestamps

    builders:
      - gerrit-git-prep
      - shell: |
          ./tools/install_cassandra_ccm.sh
      - revoke-sudo
      - tox:
          envlist: '{envlist}'
      - assert-no-extra-files

    publishers:
      - test-results
      - console-log

    node: '{node}'
