- job:
    name: gate-openstack-manuals-cli-guide
    project-type: maven
    node: precise

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/cli-guide/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'docs-draft/$JOB_NAME/$ZUUL_PIPELINE/$BUILD_NUMBER/cli/quick-start'
              source: 'doc/src/docbkx/cli-guide/target/docbkx/webhelp/cli-guide/**'
              keep-hierarchy: true
              copy-after-failure: true

- job:
    name: gate-openstack-manuals-operations-guide
    project-type: maven
    node: precise

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-ops/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'docs-draft/$JOB_NAME/$ZUUL_PIPELINE/$BUILD_NUMBER/ops/'
              source: 'doc/src/docbkx/openstack-ops/target/docbkx/webhelp/**'
              keep-hierarchy: true
              copy-after-failure: true

- job:
    name: gate-openstack-manuals-validate
    node: precise

    builders:
      - gerrit-git-prep
      - shell: "./tools/validate.py"

    publishers:
      - console-log

- job:
    name: openstack-cli-guide
    project-type: maven
    node: precise

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/cli-guide/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/cli-guide/target/docbkx/webhelp/cli-guide/**'
          target: 'cli/quick-start'
          remove-prefix: 'doc/src/docbkx/cli-guide/target/docbkx/webhelp/cli-guide/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-basic-install-fedora
    project-type: maven
    node: precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/basic-install/pom.xml
      goals: '-Doperating.system=yum -Dprofile.os=centos;fedora;rhel -Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/basic-install/target/docbkx/webhelp/**'
          target: ''
          remove-prefix: 'doc/src/docbkx/basic-install/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-basic-install-ubuntu
    project-type: maven
    node: precise

    prebuilders:
      - gerrit-git-prep

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/basic-install/pom.xml
      goals: '-Doperating.system=apt -Dprofile.os=ubuntu;debian -Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/basic-install/target/docbkx/webhelp/**'
          target: ''
          remove-prefix: 'doc/src/docbkx/basic-install/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-admin-manual-block
    project-type: maven
    node: precise

    prebuilders:
      - gerrit-git-prep

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-block-storage-admin/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-block-storage-admin/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/src/docbkx/openstack-block-storage-admin/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-glossary
    project-type: maven
    node: precise

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/common/glossary/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/common/glossary/target/docbkx/webhelp/openstack-glossary/**'
          target: 'glossary'
          remove-prefix: 'doc/src/docbkx/common/glossary/target/docbkx/webhelp/openstack-glossary/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-image-guide
    project-type: maven
    concurrent: false
    node: precise

    prebuilders:
      - gerrit-git-prep

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-image/pom.xml
      goals: '-Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-image/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/src/docbkx/openstack-image/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-config-ref
    project-type: maven
    concurrent: false
    node: precise

    prebuilders:
      - gerrit-git-prep

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-config/pom.xml
      goals: '-Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-config/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/src/docbkx/openstack-config/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'


- job:
    name: openstack-admin-manual-compute
    project-type: maven
    concurrent: false
    node: precise

    prebuilders:
      - gerrit-git-prep

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-compute-admin/pom.xml
      goals: '-Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-compute-admin/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/src/docbkx/openstack-compute-admin/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-admin-manual-netconn
    project-type: maven
    concurrent: false
    node: precise

    prebuilders:
      - gerrit-git-prep

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-network-connectivity-admin/pom.xml
      goals: '-Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-network-connectivity-admin/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/src/docbkx/openstack-network-connectivity-admin/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-admin-manual-object
    project-type: maven
    concurrent: false
    node: precise

    prebuilders:
      - gerrit-git-prep

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-object-storage-admin/pom.xml
      goals: '-Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-object-storage-admin/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/src/docbkx/openstack-object-storage-admin/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'

# in zuul/layout.yaml specified to only run against master branch.
- job:
    name: openstack-docs-site
    concurrent: false
    node: precise

    builders:
      - gerrit-git-prep

    publishers:
      - ftp:
          site: docs.openstack.org
          source: 'www/**'
          target: ''
          remove-prefix: 'www/'
          excludes: ''
      - console-log-post

# in zuul/layout.yaml specified to only run against master branch.
# The old jenkins config polled github every 5 minutes and was also triggered
# whenever a SNAPSHOT dependency was built. I have not configured that trigger
# here as being in the Zuul post queue may not play nice with that.
#
# We can use the github and snapshot dependency triggers if that is preferable.
- job:
    name: openstack-ha-guide
    project-type: maven
    concurrent: false
    node: precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - gerrit-git-prep
      - shell: |
          asciidoc -b docbook -d book -o - doc/src/docbkx/openstack-ha/ha-guide.txt |  xsltproc -o - /usr/share/xml/docbook/stylesheet/docbook5/db4-upgrade.xsl - | xmllint  --format - | sed -e 's,<book,<book xml:id="bk-ha-guide",' | sed -e 's,<info,<?rax pdf.url="../openstack-ha-guide-trunk.pdf"?><info,' > doc/src/docbkx/openstack-ha/bk-ha-guide.xml

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-ha/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-ha/target/docbkx/webhelp/trunk/**'
          target: 'trunk'
          remove-prefix: 'doc/src/docbkx/openstack-ha/target/docbkx/webhelp/trunk/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-install-deploy-guide-apt-fedora
    project-type: maven
    concurrent: false
    node: precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-install/pom.xml
      goals: '-Doperating.system=yum -Dprofile.os=centos;fedora;rhel -Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-install/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/src/docbkx/openstack-install/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-install-deploy-guide-ubuntu
    project-type: maven
    concurrent: false
    node: precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-install/pom.xml
      goals: '-Doperating.system=apt -Dprofile.os=ubuntu -Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-install/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/src/docbkx/openstack-install/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-operations-guide
    project-type: maven
    concurrent: false
    node: precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-ops/pom.xml
      goals: '-Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-ops/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/src/docbkx/openstack-ops/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'

- job:
    name: openstack-security-guide
    project-type: maven
    concurrent: false
    node: precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-security/pom.xml
      goals: '-Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/openstack-security/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/src/docbkx/openstack-security/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'
