- job:
    name: gate-openstack-manuals-operations-guide
    project-type: maven
    node: precise

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/openstack-ops/pom.xml
      goals: 'clean generate-sources -B'

    publishers:
      - console-log
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'docs-draft/$LOG_PATH/ops/'
              source: 'doc/openstack-ops/target/docbkx/webhelp/**'
              keep-hierarchy: true
              copy-after-failure: true

# in zuul/layout.yaml specified to only run against stable/grizzly
- job:
    name: gate-openstack-manuals-validate
    node: precise

    builders:
      - gerrit-git-prep
      - shell: "./tools/validate.py"

    publishers:
      - console-log

# in zuul/layout.yaml specified to only run against master branch.
- job:
    name: openstack-docs-site
    concurrent: false
    node: precise

    builders:
      - gerrit-git-prep

    publishers:
      - ftp:
          site: docs.openstack.org
          source: 'www/**'
          target: ''
          remove-prefix: 'www/'
          excludes: ''
      - console-log

# in zuul/layout.yaml specified to only run against master branch.
# The old jenkins config polled git every 5 minutes and was also triggered
# whenever a SNAPSHOT dependency was built. I have not configured that trigger
# here as being in the Zuul post queue may not play nice with that.
#
# We can use the git and snapshot dependency triggers if that is preferable.
- job:
    name: openstack-ha-guide
    project-type: maven
    concurrent: false
    node: precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - gerrit-git-prep
      - shell: |
          asciidoc -b docbook -d book -o - doc/high-availability-guide/ha-guide.txt |  xsltproc -o - /usr/share/xml/docbook/stylesheet/docbook5/db4-upgrade.xsl - | xmllint  --format - | sed -e 's,<book,<book xml:id="bk-ha-guide",' | sed -e 's,<info,<?rax pdf.url="../openstack-ha-guide-trunk.pdf"?><info,' > doc/high-availability-guide/bk-ha-guide.xml

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/high-availability-guide/pom.xml
      goals: 'clean generate-sources -B'

    publishers:
      - console-log
      - ftp:
          site: docs.openstack.org
          source: 'doc/high-availability-guide/target/docbkx/webhelp/**'
          target: ''
          remove-prefix: 'doc/high-availability-guide/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'
      - ftp:
          site: docs.openstack.org
          source: 'doc/high-availability-guide/target/docbkx/webhelp/**/atom.xml'
          target: ''
          remove-prefix: 'doc/high-availability-guide/target/docbkx/webhelp/'

- job:
    name: openstack-operations-guide
    project-type: maven
    concurrent: false
    node: precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/openstack-ops/pom.xml
      goals: '-Drelease.path.name=${DOC_RELEASE_PATH} -Dcomments.enabled=${DOC_COMMENTS_ENABLED} clean generate-sources -B'

    publishers:
      - console-log
      - ftp:
          site: docs.openstack.org
          source: 'doc/openstack-ops/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/openstack-ops/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'
      - ftp:
          site: docs.openstack.org
          source: 'doc/openstack-ops/target/docbkx/webhelp/**/atom.xml'
          target: ''
          remove-prefix: 'doc/openstack-ops/target/docbkx/webhelp/'

- job-template:
    name: 'openstack-operations-guide-{lang}'
    project-type: maven
    concurrent: false
    node: precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - gerrit-git-prep
      - shell: |
          ./tools/generatedocbook -l {lang} -b openstack-ops

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-ops-manual
      root-pom: generated/{lang}/openstack-ops/pom.xml
      goals: '-Drelease.path.name=${{DOC_RELEASE_PATH}} -Dcomments.enabled=${{DOC_COMMENTS_ENABLED}} clean generate-sources -B'

    publishers:
      - console-log
      - ftp:
          site: docs.openstack.org
          source: 'generated/{lang}/openstack-ops/target/docbkx/webhelp/**'
          target: '/{lang}/'
          remove-prefix: 'generated/{lang}/openstack-ops/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'
