- job:
    name: openstack-cli-guide
    project-type: maven
    node: precise

    triggers:
      - zuul-post

    prebuilders:
      - gerrit-git-prep

    maven:
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/cli-guide/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/src/docbkx/cli-guide/target/docbkx/webhelp/bk-cli-guide/**'
          target: 'cli/quick-start'
          remove-prefix: 'doc/src/docbkx/cli-guide/target/docbkx/webhelp/bk-cli-guide/'
          excludes: '**/*.xml,**/null*'

- job:
    name: netconn-api-v20
    project-type: maven
    node: precise

    triggers:
      - zuul-post

    prebuilders:
      - gerrit-git-prep

    maven:
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/target/docbkx/webhelp/quantum-api-2.0/quantum-api-guide/**'
          target: 'api/openstack-network/2.0/'
          remove-prefix: 'doc/target/docbkx/webhelp/quantum-api-2.0/quantum-api-guide/'
          excludes: '**/*.xml,**/null*'

- job:
    name: volume-api
    project-type: maven
    concurrent: true
    node: precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true

    triggers:
      - zuul-post

    prebuilders:
      - gerrit-git-prep

    maven:
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/target/docbkx/webhelp/volume-api-1.0/volume-api-guide/**'
          target: 'api/openstack-volume/1.0/'
          remove-prefix: 'doc/target/docbkx/webhelp/volume-api-1.0/volume-api-guide/'
          excludes: '**/*.xml,**/null*'

- job:
    name: images-api-v20
    project-type: maven
    concurrent: true
    node: precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true

    triggers:
      - zuul-post

    prebuilders:
      - gerrit-git-prep
      - markdown-docbook
          filename: "images-api-v2.0"

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    maven:
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: openstack-image-service-api/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/target/docbkx/webhelp/images-api-2.0/**'
          target: 'api/openstack-image-service/2.0/'
          remove-prefix: 'doc/target/docbkx/webhelp/images-api-2.0/'
          excludes: '**/*.xml,**/null*'
          
- job:
    name: openstackapi-programming
    project-type: maven
    concurrent: true
    node: precise

    wrappers:
      - timeout:
          timeout: 40
          fail: true

    triggers:
      - zuul-post

    prebuilders:
      - gerrit-git-prep
      - markdown-docbook
          filename: "openstackapi-programming"

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    maven:
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/src/docbkx/openstack-api-programming/pom.xml
      goals: 'clean generate-sources'

    publishers:
      - console-log-post
      - ftp:
          site: docs.openstack.org
          source: 'doc/target/docbkx/webhelp/openstack-api-programming/**'
          target: 'api/openstack-compute/programmer/'
          remove-prefix: 'doc/target/docbkx/webhelp/openstack-api-programming/'
          excludes: '**/*.xml,**/null*'          
