- job-template:
    name: 'openstack-install-deploy-guide-{lang}'

    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          source /usr/local/jenkins/slave_scripts/select-mirror.sh openstack openstack-manuals
          tox -v -e buildlang-install -- {lang}

    publishers:
      - console-log
      - upload-to-docs-site

- job-template:
    name: 'openstack-misc-guides-{lang}'

    node: 'bare-precise || bare-trusty'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          source /usr/local/jenkins/slave_scripts/select-mirror.sh openstack openstack-manuals
          tox -v -e buildlang-misc -- {lang}

    publishers:
      - console-log
      - upload-to-docs-site

- job-template:
    name: 'openstack-operations-guide-{lang}'
    node: '{node}'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          source /usr/local/jenkins/slave_scripts/select-mirror.sh openstack operations-guide
          tox -v -e buildlang -- {lang}

    publishers:
      - console-log
      - upload-to-docs-site

- job-template:
    name: 'security-doc-{lang}'
    node: '{node}'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          source /usr/local/jenkins/slave_scripts/select-mirror.sh openstack security-doc
          tox -v -e buildlang -- {lang}

    publishers:
      - console-log
      - upload-to-docs-site

- job-template:
    name: 'gate-{name}-tox-doc-publish-{envlist}'

    wrappers:
      - build-timeout:
          timeout: 40
      - timestamps

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - tox:
          envlist: '{envlist}'
          github-org: '{github-org}'
          project: '{name}'
      - assert-no-extra-files

    publishers:
      - console-log
      - upload-docs-draft
      - upload-doc-build-results

    node: '{node}'

- job-group:
    name: openstack-doc-jobs
    jobs:
      - gate-{name}-tox-{envlist}:
          envlist: checkniceness
      - gate-{name}-tox-{envlist}:
          envlist: checksyntax
      - gate-{name}-tox-{envlist}:
          envlist: checkdeletions
      - gate-{name}-tox-doc-publish-{envlist}:
          envlist: checkbuild
