- job-template:
    name: 'openstack-{manual}'
    project-type: maven
    node: bare-precise

    prebuilders:
      - revoke-sudo
      - gerrit-git-prep

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/{manual}/pom.xml
      goals: '-Drelease.path.name=${{DOC_RELEASE_PATH}} -Dcomments.enabled=${{DOC_COMMENTS_ENABLED}} clean generate-sources -B'

    publishers:
      - console-log
      - ftp:
          site: docs.openstack.org
          source: 'doc/{manual}/target/docbkx/webhelp/**'
          target: ''
          remove-prefix: 'doc/{manual}/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'
      - ftp:
          site: docs.openstack.org
          source: 'doc/{manual}/target/docbkx/webhelp/**/atom.xml'
          target: ''
          remove-prefix: 'doc/{manual}/target/docbkx/webhelp/'

- job-template:
    name: 'openstack-install-deploy-guide-{distribution}'

    project-type: maven
    node: bare-precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    prebuilders:
      - revoke-sudo
      - gerrit-git-prep

    maven:
      maven-name: Maven3
      root-module:
        group-id: org.openstack.docs
        artifact-id: openstack-guide
      root-pom: doc/install-guide/pom.xml
      goals: '-Doperating.system={system} -Dprofile.os={profileos} -Drelease.path.name=${{DOC_RELEASE_PATH}} -Dcomments.enabled=${{DOC_COMMENTS_ENABLED}} clean generate-sources -B'

    publishers:
      - console-log
      - ftp:
          site: docs.openstack.org
          source: 'doc/install-guide/target/docbkx/webhelp/**'
          target: '/'
          remove-prefix: 'doc/install-guide/target/docbkx/webhelp/'
          excludes: '**/*.xml,**/null*'
      - ftp:
          site: docs.openstack.org
          source: 'doc/install-guide/target/docbkx/webhelp/**/atom.xml'
          target: '/'
          remove-prefix: 'doc/install-guide/target/docbkx/webhelp/'

- job-template:
    name: 'openstack-install-deploy-guide-{lang}'

    node: bare-precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          source /usr/local/jenkins/slave_scripts/select-mirror.sh openstack openstack-manuals
          tox -v -e buildlang-install -- {lang}

    publishers:
      - console-log
      - ftp:
          site: docs.openstack.org
          source: 'publish-docs/{lang}/**'
          target: '/{lang}/'
          remove-prefix: 'publish-docs/{lang}/'

- job-template:
    name: 'openstack-misc-guides-{lang}'

    node: bare-precise

    properties:
      - inject:
          script-file: /usr/local/jenkins/slave_scripts/docbook-properties.sh
          properties-file: gerrit-doc.properties

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          source /usr/local/jenkins/slave_scripts/select-mirror.sh openstack openstack-manuals
          tox -v -e buildlang-misc -- {lang}

    publishers:
      - console-log
      - ftp:
          site: docs.openstack.org
          source: 'publish-docs/{lang}/**'
          target: '/{lang}/'
          remove-prefix: 'publish-docs/{lang}/'

- job-template:
    name: 'gate-{name}-tox-doc-publish-{envlist}'

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - tox:
          envlist: '{envlist}'
          github-org: '{github-org}'
          project: '{name}'
      - assert-no-extra-files

    publishers:
      - console-log
      - upload-docs-draft
      - upload-doc-build-results

    node: '{node}'

- job-group:
    name: openstack-doc-jobs
    jobs:
      - gate-{name}-tox-{envlist}:
          envlist: checkniceness
      - gate-{name}-tox-{envlist}:
          envlist: checksyntax
      - gate-{name}-tox-{envlist}:
          envlist: checkdeletions
      - gate-{name}-tox-doc-publish-{envlist}:
          envlist: checkbuild
