- job:
    name: 'periodic-mirror-python26'
    node: mirror26

    wrappers:
      - timeout:
          timeout: 90
          fail: true
      - timestamps

    builders:
      - update-pypi-mirror
      - link-logs

    publishers:
      - console-log


- job:
    name: 'post-mirror-python26'
    node: mirror26

    wrappers:
      - timeout:
          timeout: 90
          fail: true
      - timestamps

    builders:
      - update-pypi-mirror
      - link-logs

    publishers:
      - console-log


- job:
    name: 'periodic-mirror-python27'
    node: mirror27

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - update-pypi-mirror
      - link-logs

    publishers:
      - console-log


- job:
    name: 'post-mirror-python27'
    node: mirror27

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - update-pypi-mirror
      - link-logs

    publishers:
      - console-log


- job:
    name: 'periodic-mirror-python33'
    node: mirror33

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - update-pypi-mirror
      - link-logs

    publishers:
      - console-log


- job:
    name: 'post-mirror-python33'
    node: mirror33

    wrappers:
      - timeout:
          timeout: 60
          fail: true
      - timestamps

    builders:
      - update-pypi-mirror
      - link-logs

    publishers:
      - console-log
