- job:
    name: gate-noop
    node: precise

- job:
    name: gate-django_openstack_auth-noop
    node: precise

- job:
    name: gate-grenade-noop
    node: precise

- job-template:
    name: 'gate-{name}-run-tests'

    builders:
      - gerrit-git-prep
      - run-tests:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - console-log

    node: '{node}'

- job-template:
    name: 'gate-{name}-tox-{env}'

    builders:
      - gerrit-git-prep
      - shell: '/usr/local/jenkins/slave_scripts/run-tox.sh {env}'
      - assert-no-extra-files

    publishers:
      - test-results
      - console-log

    node: '{node}'
