- job:
    name: node-test

    parameters:
      - label:
          name: NODE
          description: Node to test

    builders:
      - shell: 'echo ok'

- job-template:
    name: 'gate-{name}-run-tests'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - run-tests:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - console-log

    node: '{node}'

- job-template:
    name: 'gate-{name}-bash8'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - bash8:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - console-log

    node: '{node}'

- job-template:
    name: 'gate-{name}-unittests-{env}'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: '/usr/local/jenkins/slave_scripts/run-unittests.sh {env} {github-org} {name}'
      - assert-no-extra-files

    publishers:
      - test-results
      - console-log

    node: '{node}'

- job:
    name: 'sandbox-tag'

    builders:
      - revoke-sudo
      - gerrit-git-prep

    publishers:
      - console-log

    node: 'bare-precise'
