- job:
    name: gate-murano-devstack-dsvm
    node: 'devstack-precise || devstack-trusty'

    wrappers:
      - build-timeout:
          timeout: 65
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=60
          export ENABLED_SERVICES=murano,murano-api,murano-engine,tempest
          export PROJECTS="stackforge/murano $PROJECTS"
          export PROJECTS="stackforge/murano-dashboard $PROJECTS"
          export PROJECTS="stackforge/python-muranoclient $PROJECTS"

          function pre_test_hook {
              cd /opt/stack/new/murano/functionaltests
              ./pre_test_hook.sh
          }
          export -f pre_test_hook

          function post_test_hook {
              cd /opt/stack/new/murano/functionaltests
              ./post_test_hook.sh
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log
