- job-template:
    name: '{pipeline}-neutron-dsvm-api{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 125
          fail: true
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=120
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          export BRANCH_OVERRIDE={branch-override}
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function post_test_hook {{
              cd $BASE/new/neutron
              # Ensure that the executing user can invoke tox on the
              # neutron source tree.
              sudo chown -R tempest:stack $BASE/new/neutron
              echo "Configuring venv for neutron api test suite"
              # Manually install tempest pending a decision on how
              # best to include tempest as an explicit test dependency
              # of neutron.
              sudo -H -u tempest tox -e api --notest
              sudo -H -u tempest .tox/api/bin/pip install -e $BASE/new/tempest
              echo "Running neutron api test suite"
              sudo -H -u tempest tempest tox -e api
          }}
          export -f post_test_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log
