- job:
    name: 'check-nova-docker-dsvm-f20'
    node: 'devstack-f20'

    wrappers:
      - timeout:
          timeout: 65
          fail: true
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          function gate_hook {
              $BASE/new/nova-docker/contrib/devstack/gate_hook.sh
          }

          function post_test_hook {
              $BASE/new/nova-docker/contrib/devstack/post_test_hook.sh
          }

          export -f gate_hook
          export -f post_test_hook

          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=60
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_TEMPEST_FULL=0
          export RE_EXEC=false
          export PROJECTS="stackforge/nova-docker $PROJECTS"
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$LOG_PATH'
              source: 'logs/**'
              keep-hierarchy: false
              copy-after-failure: true
      - console-log
