# Not using the template because openstack-planet does not use tox.
- job:
    name: 'gate-openstack-planet-unittest'
    node: bare-precise

    builders:
      - gerrit-git-prep
      - shell: |
          python test.py

    publishers:
      - console-log
