- job:
    name: gate-openstackid-unittests
    node: 'bare-precise'

    builders:
        - revoke-sudo
        - gerrit-git-prep
        - shell: |
            #!/bin/bash -xe
            /usr/local/jenkins/slave_scripts/php-laravel-build.sh
    publishers:
        - console-log
        - coverage-log
        - scp:
            site: 'static.openstack.org'
            files:
                - target: 'logs/$LOG_PATH'
                  source: './reports/**'
                  keep-hierarchy: true
                  copy-after-failure: true

- job-template:
    name: 'openstackid-release-{branch-designator}'
    node: '{node}'

    builders:
        - revoke-sudo
        - gerrit-git-prep
        - shell: |
            #!/bin/bash -xe
            /usr/local/jenkins/slave_scripts/version-properties.sh
        - shell: |
            #!/bin/bash -xe
            source version.properties
            /usr/local/jenkins/slave_scripts/php-laravel-build.sh
            # Clone to dist
            rm -rf dist
            mkdir dist
            rsync -arv --exclude ".git*" --exclude tarballs --exclude dist . dist
            # Clean/create a tarball directory
            rm -rf tarballs
            mkdir -p tarballs
            # Create an archive tarball.
            tar -czf openstackid-$PROJECT_VER.tar.gz dist/
            cp openstackid-$PROJECT_VER.tar.gz tarballs/openstackid-latest.tar.gz
            mv openstackid-$PROJECT_VER.tar.gz tarballs/
    publishers:
        - console-log
        - coverage-log
        - scp:
            site: 'static.openstack.org'
            files:
                - target: 'logs/$LOG_PATH'
                  source: './reports/**'
                  keep-hierarchy: true
                  copy-after-failure: true
                - target: 'tarballs/openstackid/'
                  source: 'tarballs/*.tar.gz'
                  keep-hierarchy: false
                  copy-after-failure: false
