- job-template:
    name: '{pipeline}-{injectedlib}-dsvm-{name}{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 95
          fail: true
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=95
          export PROJECTS="{injectedrepo} $PROJECTS"
          export BRANCH_OVERRIDE={branch-override}
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function gate_hook {{
              cd /opt/stack/new/$(basename {injectedrepo})
              remaining_time
              timeout -s 9 ${{REMAINING_TIME}}m ./tools/run_cross_tests.sh /opt/stack/new/{name} py27
          }}
          export -f gate_hook

          function post_test_hook {{
              cd /opt/stack/new/{name}
              mv nose_results.html $WORKSPACE/logs
              mv testr_results.html.gz $WORKSPACE/logs
              mv .testrepository/tmp* $WORKSPACE/logs
              mv subunit_log.txt.gz $WORKSPACE/logs
          }}
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log


- job-group:
    name: oslotest-cross-test

    injectedlib: oslotest
    injectedrepo: openstack/oslo.test

    jobs:
      - '{pipeline}-{injectedlib}-dsvm-{name}{branch-designator}':
          pipeline: check
          node: 'devstack-precise || devstack-precise-check'
          branch-designator: ''
          branch-override: default
      - '{pipeline}-{injectedlib}-dsvm-{name}{branch-designator}':
          pipeline: gate
          node: devstack-precise
          branch-designator: ''
          branch-override: default
