- job:
    name: gate-pbr-devstack-vm-rawinstall
    node: devstack-precise

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    parameters:
      - label:
          name: NODE_LABEL
          description: Label of node to use for this build
          default: devstack-precise

    builders:
      - devstack-inprogress
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          function post_test_hook {
              bash -xe $BASE/new/pbr/tools/integration.sh $PROJECTS $BASE
          }
          export -f post_test_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '/home/jenkins/.pip/pip.log'
              keep-hierarchy: false
              copy-after-failure: true
      - console-log
      - devstack-complete
