- project:
    name: climate
    github-org: stackforge
    node: quantal

    jobs:
      - gate-{name}-pep8
      - gate-{name}-python26
      - gate-{name}-python27

- project:
    name: config
    github-org: openstack-infra
    node: quantal

    jobs:
      - gate-{name}-puppet-lint
      - gate-{name}-puppet-syntax
      - gate-{name}-pyflakes

- project:
    name: savanna
    github-org: stackforge
    node: quantal
    rtfd-id: 7095
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs
      - gate-{name}-pyflakes
      - hook-{name}-rtfd
      - pypi-jobs

- project:
    name: python-savannaclient
    github-org: stackforge
    node: quantal
    rtfd-id: 7106
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs
      - gate-{name}-pyflakes
      - hook-{name}-rtfd
      - pypi-jobs

- project:
    name: kwapi
    github-org: stackforge
    node: quantal

    jobs:
      - gate-{name}-pep8

- project:
    name: ceilometer
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-grizzly-bitrot-jobs
      - openstack-publish-jobs
      - translation-jobs

- project:
    name: cinder
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-grizzly-bitrot-jobs
      - openstack-publish-jobs


- project:
    name: compute-api
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs
      - openstack-compute-api-doc


- project:
    name: hacking
    github-org: openstack-dev
    node: quantal
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs
      - pypi-jobs


- project:
    name: pbr
    github-org: openstack-dev
    node: quantal
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs
      - pypi-jobs


- project:
    name: gerritbot
    github-org: openstack-infra
    node: quantal
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - gate-{name}-pep8
      - gate-{name}-pyflakes
      - '{name}-tarball'
      - pypi-jobs


- project:
    name: statusbot
    github-org: openstack-infra
    node: quantal
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - gate-{name}-pep8
      - gate-{name}-pyflakes
      - '{name}-tarball'
      - pypi-jobs


- project:
    name: gerritlib
    github-org: openstack-infra
    node: quantal
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - gate-{name}-pep8
      - gate-{name}-pyflakes
      - '{name}-tarball'
      - pypi-jobs


- project:
    name: jeepyb
    github-org: openstack-infra
    node: quantal
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - gate-{name}-pep8
      - gate-{name}-pyflakes
      - '{name}-tarball'
      - pypi-jobs


- project:
    name: gear
    github-org: openstack-infra
    node: quantal
    tarball-site: tarballs.openstack.org
    rtfd-id: 6926

    jobs:
      - python-jobs
      - pypi-jobs
      - hook-{name}-rtfd


- project:
    name: gearman-plugin
    maven-group-id: org.jenkins-ci.plugins
    github-org: openstack-infra
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - jenkins-plugin-jobs


- project:
    name: zmq-event-publisher
    maven-group-id: org.jenkins-ci.plugins
    github-org: openstack-infra
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - jenkins-plugin-jobs


- project:
    name: git-review
    github-org: openstack-infra
    node: quantal
    tarball-site: tarballs.openstack.org
    jobs:
      - gate-{name}-pep8
      - '{name}-branch-tarball'
      - '{name}-tarball'
      - pypi-jobs


- project:
    name: glance
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-folsom-bitrot-jobs
      - python-grizzly-bitrot-jobs
      - openstack-publish-jobs
      - translation-jobs


- project:
    name: heat
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-grizzly-bitrot-jobs
      - openstack-publish-jobs


- project:
    name: python-heatclient
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: heat-cfntools
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: horizon
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-folsom-bitrot-jobs
      - python-grizzly-bitrot-jobs
      - openstack-publish-jobs


- project:
    name: identity-api
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs
      - identity-api-v20


- project:
    name: image-api
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs
      - image-api-v11


- project:
    name: jenkins-job-builder
    github-org: openstack-infra
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - gate-{name}-pep8
      - gate-{name}-pyflakes
      - gate-{name}-docs
      - '{name}-branch-tarball'
      - '{name}-tarball'
      - pypi-jobs

- project:
    name: keystone
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-folsom-bitrot-jobs
      - python-grizzly-bitrot-jobs
      - openstack-publish-jobs
      - translation-jobs


- project:
    name: netconn-api
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs
      - network-api-v10


- project:
    name: netconn-api-v20
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs


- project:
    name: nose-html-output
    github-org: openstack-infra
    node: quantal
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - '{name}-tarball'
      - pypi-jobs


- project:
    name: nova
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-folsom-bitrot-jobs
      - python-grizzly-bitrot-jobs
      - openstack-publish-jobs
      - gate-{name}-pylint
      - translation-jobs


- project:
    name: object-api
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs
      - openstack-object-api-doc


- project:
    name: oslo.config
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs
      - gate-{name}-pyflakes


- project:
    name: oslo-incubator
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - gate-{name}-pyflakes


- project:
    name: python-ceilometerclient
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-cinderclient
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-glanceclient
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-keystoneclient
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-novaclient
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-openstackclient
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-quantumclient
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-swiftclient
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: quantum
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-grizzly-bitrot-jobs
      - openstack-publish-jobs
      - translation-jobs


- project:
    name: reddwarf
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: quantal

    jobs:
      - python-jobs


- project:
    name: python-reddwarfclient
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: quantal

    jobs:
      - python-jobs
      - pypi-jobs


- project:
    name: libra
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: quantal

    jobs:
      - python-jobs

- project:
    name: python-libraclient
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: quantal

    jobs:
      - python-jobs

- project:
    name: healthnmon
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: quantal

    jobs:
      - python-jobs


- project:
    name: marconi
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: quantal

    jobs:
      - python-jobs


- project:
    name: moniker
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org
    rtfd-id: 5190

    jobs:
      - python-jobs
      - hook-{name}-rtfd
      - gate-{name}-pyflakes
      - pypi-jobs


- project:
    name: packstack
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs


- project:
    name: python-monikerclient
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org
    rtfd-id: 5366

    jobs:
      - python-jobs
      - hook-{name}-rtfd
      - gate-{name}-pyflakes
      - pypi-jobs


- project:
    name: bufunfa
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org
    rtfd-id: 5216

    jobs:
      - python-jobs
      - hook-{name}-rtfd


- project:
    name: reviewday
    github-org: openstack-infra
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs
      - gate-{name}-pyflakes
      - pypi-jobs


- project:
    name: swift
    github-org: openstack
    node: quantal
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
# No one is interested in stable/ branches on swift, so don't run bitrot jobs


- project:
    name: tempest
    github-org: openstack-infra
    node: quantal

    jobs:
      - gate-{name}-pep8
      - gate-{name}-requirements


- project:
    name: zuul
    github-org: openstack-infra
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs
      - gate-{name}-pyflakes
      - pypi-jobs


- project:
    name: devstack-node-provider-rackspace
    provider: rackspace
    jobs:
      - devstack-node-provider-jobs


- project:
    name: devstack-node-provider-rackspace-dfw
    provider: rackspace-dfw
    jobs:
      - devstack-node-provider-jobs


- project:
    name: devstack-node-provider-rackspace-ord
    provider: rackspace-ord
    jobs:
      - devstack-node-provider-jobs


- project:
    name: devstack-node-provider-hpcloud-az1
    provider: hpcloud-az1
    jobs:
      - devstack-node-provider-jobs


- project:
    name: devstack-node-provider-hpcloud-az2
    provider: hpcloud-az2
    jobs:
      - devstack-node-provider-jobs

- project:
    name: devstack-node-provider-hpcloud-az3
    provider: hpcloud-az3
    jobs:
      - devstack-node-provider-jobs

- project:
    name: diskimage-builder
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs

- project:
    name: os-config-applier
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs

- project:
    name: os-refresh-config
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs

- project:
    name: tripleo-image-elements
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs


- project:
    name: puppet-glance
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - puppet-module-unit


- project:
    name: puppet-keystone
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - puppet-module-unit


- project:
    name: puppet-cinder
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - puppet-module-unit


- project:
    name: puppet-nova
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - puppet-module-unit


- project:
    name: puppet-horizon
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - puppet-module-unit


- project:
    name: puppet-openstack
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - puppet-module-unit


- project:
    name: puppet-swift
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - puppet-module-unit

- project:
    name: puppet-quantum
    github-org: stackforge
    node: quantal
    tarball-site: tarballs.openstack.org

    jobs:
      - puppet-module-unit

- project:
    name: python-marconiclient
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: quantal

    jobs:
      - python-jobs
