- project:
    name: kwapi
    github-org: stackforge
    node: precise

    jobs:
      - gate-{name}-pep8

- project:
    name: ceilometer
    github-org: openstack
    node: oneiric
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-jobs-folsom
      - openstack-publish-jobs

- project:
    name: cinder
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs


- project:
    name: compute-api
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs
      - openstack-compute-api-doc


- project:
    name: gerritbot
    github-org: openstack-infra
    node: precise
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - gate-{name}-pep8
      - gate-{name}-pyflakes
      - pypi-jobs


- project:
    name: gerritlib
    github-org: openstack-infra
    node: precise
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - gate-{name}-pep8
      - gate-{name}-pyflakes
      - pypi-jobs


- project:
    name: jeepyb
    github-org: openstack-infra
    node: precise
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - gate-{name}-pep8
      - gate-{name}-pyflakes
      - pypi-jobs


- project:
    name: gearman-plugin
    github-org: openstack-infra
    node: precise
    tarball-site: tarballs.openstack.org


- project:
    name: git-review
    github-org: openstack-infra
    node: precise
    jobs:
      - gate-{name}-pep8


- project:
    name: glance
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-diablo-bitrot-jobs
      - python-essex-bitrot-jobs
      - python-folsom-bitrot-jobs
      - openstack-publish-jobs


- project:
    name: heat
    github-org: openstack
    node: oneiric
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs


- project:
    name: python-heatclient
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: horizon
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-diablo-bitrot-jobs
      - python-essex-bitrot-jobs
      - python-folsom-bitrot-jobs
      - openstack-publish-jobs


- project:
    name: identity-api
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs
      - identity-api-v20


- project:
    name: image-api
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs
      - image-api-v11


- project:
    name: jenkins-job-builder
    github-org: openstack-infra
    node: precise
    tarball-site: tarballs.openstack.org

    jobs:
      - gate-{name}-pep8
      - gate-{name}-pyflakes
      - gate-{name}-docs
      - pypi-jobs

- project:
    name: keystone
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-diablo-bitrot-jobs
      - python-essex-bitrot-jobs
      - python-folsom-bitrot-jobs
      - openstack-publish-jobs
      - translation-jobs


- project:
    name: netconn-api
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs
      - network-api-v10


- project:
    name: netconn-api-v20
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs


- project:
    name: nose-html-output
    github-org: openstack-infra
    node: precise
    doc-publisher-site: ci.openstack.org
    tarball-site: tarballs.openstack.org

    jobs:
      - pypi-jobs


- project:
    name: nova
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - python-diablo-bitrot-jobs
      - python-essex-bitrot-jobs
      - python-folsom-bitrot-jobs
      - openstack-publish-jobs
      - gate-{name}-pylint
      - translation-jobs


- project:
    name: object-api
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - api-jobs
      - openstack-object-api-doc


- project:
    name: oslo-incubator
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - gate-{name}-pyflakes


- project:
    name: python-ceilometerclient
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-cinderclient
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-glanceclient
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-keystoneclient
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-novaclient
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-openstackclient
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-quantumclient
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: python-swiftclient
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
      - pypi-jobs


- project:
    name: quantum
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs


- project:
    name: reddwarf
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: precise

    jobs:
      - python-jobs


- project:
    name: python-reddwarfclient
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: precise

    jobs:
      - python-jobs


- project:
    name: libra
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: precise

    jobs:
      - python-jobs

- project:
    name: python-libraclient
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: precise

    jobs:
      - python-jobs

- project:
    name: healthnmon
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: precise

    jobs:
      - python-jobs


- project:
    name: marconi
    github-org: stackforge
    tarball-site: tarballs.openstack.org
    node: precise

    jobs:
      - python-jobs


- project:
    name: moniker
    github-org: stackforge
    node: precise
    tarball-site: tarballs.openstack.org
    rtfd-id: 5190

    jobs:
      - python-jobs
      - hook-{name}-rtfd
      - gate-{name}-pyflakes
      - pypi-jobs


- project:
    name: python-monikerclient
    github-org: stackforge
    node: precise
    tarball-site: tarballs.openstack.org
    rtfd-id: 5366

    jobs:
      - python-jobs
      - hook-{name}-rtfd
      - gate-{name}-pyflakes
      - pypi-jobs


- project:
    name: bufunfa
    github-org: stackforge
    node: precise
    tarball-site: tarballs.openstack.org
    rtfd-id: 5216

    jobs:
      - python-jobs
      - hook-{name}-rtfd


- project:
    name: swift
    github-org: openstack
    node: precise
    tarball-site: tarballs.openstack.org
    doc-publisher-site: docs.openstack.org

    jobs:
      - python-jobs
      - openstack-publish-jobs
# No one is interested in stable/ branches on swift, so don't run bitrot jobs


- project:
    name: tempest
    github-org: openstack-infra
    node: precise

    jobs:
      - gate-{name}-pep8


- project:
    name: zuul
    github-org: openstack-infra
    node: precise
    tarball-site: tarballs.openstack.org

    jobs:
      - python-jobs
      - gate-{name}-pyflakes
      - pypi-jobs


- project:
    name: devstack-node-provider-rackspace
    provider: rackspace
    jobs:
      - devstack-node-provider-jobs


- project:
    name: devstack-node-provider-rackspace-nova
    provider: rackspace-nova
    jobs:
      - devstack-node-provider-jobs


- project:
    name: devstack-node-provider-rackspace-ord
    provider: rackspace-ord
    jobs:
      - devstack-node-provider-jobs


- project:
    name: devstack-node-provider-hpcloud-az1
    provider: hpcloud-az1
    jobs:
      - devstack-node-provider-jobs


- project:
    name: devstack-node-provider-hpcloud-az2
    provider: hpcloud-az2
    jobs:
      - devstack-node-provider-jobs
