- job-template:
    name: 'periodic-{name}-python26-{branch-name}'

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    builders:
      - python26:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/periodic/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*nose_results.html'
              keep-hierarchy: false
              copy-after-failure: true
      - console-log-periodic
      - email:
          recipients: '{email}'

    scm:
      - git:
          url: 'git://git.openstack.org/{github-org}/{name}'
          branches:
            - 'origin/{branch}'

    node: centos6


- job-template:
    name: 'periodic-{name}-python27-{branch-name}'

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    builders:
      - python27:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/periodic/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*nose_results.html'
              keep-hierarchy: false
              copy-after-failure: true
      - console-log-periodic
      - email:
          recipients: '{email}'

    scm:
      - git:
          url: 'git://git.openstack.org/{github-org}/{name}'
          branches:
            - 'origin/{branch}'

    node: '{node}'


- job-template:
    name: 'periodic-{name}-docs-{branch-name}'

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    builders:
      - docs:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - console-log-periodic
      - email:
          recipients: '{email}'

    scm:
      - git:
          url: 'git://git.openstack.org/{github-org}/{name}'
          branches:
            - 'origin/{branch}'

    node: '{node}'


- job-group:
    name: python-grizzly-bitrot-jobs
    branch: 'stable/grizzly'
    branch-name: 'stable-grizzly'
    email: openstack-stable-maint@lists.openstack.org
    node: precise
    jobs:
      - 'periodic-{name}-python26-{branch-name}'
      - 'periodic-{name}-python27-{branch-name}'
      - 'periodic-{name}-docs-{branch-name}'


- job-group:
    name: python-havana-bitrot-jobs
    branch: 'stable/havana'
    branch-name: 'stable-havana'
    email: openstack-stable-maint@lists.openstack.org
    node: precise
    jobs:
      - 'periodic-{name}-python26-{branch-name}'
      - 'periodic-{name}-python27-{branch-name}'
      - 'periodic-{name}-docs-{branch-name}'
