- job-template:
    name: '{name}-coverage'

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    triggers:
      - zuul-post

    builders:
      - gerrit-git-prep
      - coverage:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - coverage-log-post
      - console-log-post

    node: '{node}'


- job-template:
    name: 'gate-{name}-pep8'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - pep8:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - pep8
      - console-log

    node: '{node}'


- job-template:
    name: 'gate-{name}-pylint'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - pylint:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - pylint
      - console-log

    node: '{node}'


- job-template:
    name: 'gate-{name}-python26'

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - python26:
          github-org: '{github-org}'
          project: '{name}'
      - assert-no-extra-files

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*nose_results.html'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*testr_results.html.gz'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '.testrepository/tmp*'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*subunit_log.txt.gz'
              keep-hierarchy: false
              copy-after-failure: true
      - console-log

    # >= precise does not have python2.6
    node: oneiric

# temporary/non-voting while we burn in rhel6 slaves for havana
- job-template:
    name: 'gate-{name}-python26-rhel6'

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - python26:
          github-org: '{github-org}'
          project: '{name}'
      - assert-no-extra-files

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*nose_results.html'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*testr_results.html.gz'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '.testrepository/tmp*'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*subunit_log.txt.gz'
              keep-hierarchy: false
              copy-after-failure: true
      - console-log

    node: rhel6

- job-template:
    name: 'gate-{name}-python27'

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    parameters:
      - label:
          name: NODE_LABEL
          description: Label of node to use for this build
          default: '{node}'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - python27:
          github-org: '{github-org}'
          project: '{name}'
      - assert-no-extra-files

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*nose_results.html'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*testr_results.html.gz'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '.testrepository/tmp*'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*subunit_log.txt.gz'
              keep-hierarchy: false
              copy-after-failure: true
      - console-log

    node: '{node}'

- job-template:
    name: 'gate-{name}-docs'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - docs:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - console-log

    node: '{node}'


- job-template:
    name: 'gate-{name}-pyflakes'
    node: quantal

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - pyflakes:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - console-log


- job-template:
    name: '{name}-tarball'
    node: quantal

    triggers:
      - zuul-post

    builders:
      - gerrit-git-prep
      - tarball:
          github-org: '{github-org}'
          project: '{name}'

    publishers:
      - tarball:
          project: '{name}'
          site: '{tarball-site}'
      - console-log-post


- job-template:
    name: '{name}-branch-tarball'
    concurrent: false
    node: quantal

    triggers:
      - zuul-post

    builders:
      - gerrit-git-prep
      - tarball:
          github-org: '{github-org}'
          project: '{name}'
      - shell: |
          #!/bin/bash -xe
          BRANCH=$ZUUL_REFNAME
          BRANCH_PATH=`echo $BRANCH | tr / -`
          mv dist/* dist/{name}-$BRANCH_PATH.tar.gz

    publishers:
      - tarball:
          project: '{name}'
          site: '{tarball-site}'
      - console-log-post


- job-template:
    name: 'gate-{name}-requirements'
    node: quantal

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/project-requirements-change.py $ZUUL_BRANCH

    publishers:
      - console-log


- job-group:
    name: python-jobs
    jobs:
      - '{name}-coverage'
      - 'gate-{name}-pep8'
      - 'gate-{name}-python26'
      - 'gate-{name}-python26-rhel6'
      - 'gate-{name}-python27'
      - 'gate-{name}-docs'
      - 'gate-{name}-requirements'
      - '{name}-tarball'
      - '{name}-branch-tarball'
      # pyflakes isn't standard
      # pylint isn't standard
