- job-template:
    name: '{name}-coverage'

    triggers:
      - zuul-post

    builders:
      - gerrit-git-prep
      - coverage

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/periodic/$JOB_NAME/$BUILD_NUMBER'
              source: 'cover/**'
              keep-hierarchy: true
              copy-after-failure: true
            - target: 'logs/periodic/$JOB_NAME/$BUILD_NUMBER'
              copy-console: true
              copy-after-failure: true

    node: '{node}'
  

- job-template:
    name: 'gate-{name}-pep8'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - pep8

    publishers:
      - pep8
      - console-log

    node: '{node}'
  

- job-template:
    name: 'gate-{name}-pylint'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - pylint

    publishers:
      - pylint
      - console-log

    node: '{node}'


- job-template:
    name: 'gate-{name}-python26'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - python26

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*nose_results.html'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              copy-console: true
              copy-after-failure: true

    # >= precise does not have python2.6
    node: oneiric
  

- job-template:
    name: 'gate-{name}-python27'

    parameters:
      - label:
          name: NODE_LABEL
          description: Label of node to use for this build
          default: '{node}'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - python27

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: '**/*nose_results.html'
              keep-hierarchy: false
              copy-after-failure: true
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              copy-console: true
              copy-after-failure: true

    node: '{node}'
  

- job-template:
    name: 'gate-{name}-merge'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep

    publishers:
      - console-log

    node: '{node}'


- job-template:
    name: 'gate-{name}-docs'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - docs

    publishers:
      - console-log

    node: '{node}'

  
- job-template:
    name: 'gate-{name}-pyflakes'
    node: precise

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - pyflakes

    publishers:
      - console-log


- job-group:
    name: python-jobs
    jobs:
      - '{name}-coverage'
      - 'gate-{name}-merge'
      - 'gate-{name}-pep8'
      - 'gate-{name}-python26'
      - 'gate-{name}-python27'
      - 'gate-{name}-docs'
      # pyflakes isn't standard
      # pylint isn't standard
