- job-template:
    name: gate-requirements-integration-{mirror}
    node: devstack-precise

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    parameters:
      - label:
          name: NODE_LABEL
          description: Label of node to use for this build
          default: devstack-precise

    builders:
      - devstack-inprogress
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          if [ "{mirror}" == "no-mirror" ]; then
              MIRROR="--no-mirror"
          fi
          function gate_hook (
              bash $GATE_SCRIPT_DIR/devstack-vm-gate.sh && \
              bash -xe $BASE/new/pbr/tools/integration.sh $MIRROR $PROJECTS
          )
          export -f gate_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$BASE_LOG_PATH/$JOB_NAME/$BUILD_NUMBER'
              source: '**/pip.log'
              keep-hierarchy: false
              copy-after-failure: true
      - console-log
      - devstack-complete
