- job:
    name: gate-requirements-install
    node: precise

    builders:
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          source /usr/local/jenkins/slave_scripts/select-mirror.sh openstack requirements
          virtualenv --clear .venv
          FILE="global-requirements.txt"
          # Ignore lines beginning with https?:// just as the mirror script does.
          sed -e '/^https\?:\/\//d' $FILE > $FILE.clean
          # Run the same basic pip command that the mirror script runs.
          .venv/bin/pip install -M -U --exists-action=w -r $FILE.clean
          if [ -e dev-requirements.txt ] ; then
              .venv/bin/pip install -M -U --exists-action=w -r dev-requirements.txt
          fi

          # Print all installed stuff to demonstrate versions
          .venv/bin/pip freeze

    publishers:
      - console-log

- job:
    name: propose-requirements-updates
    node: proposal
    concurrent: false

    builders:
      - gerrit-git-prep
      - shell: /usr/local/jenkins/slave_scripts/propose_requirements_update.sh
      - link-logs

    publishers:
      - console-log
