- job:
    name: gate-requirements-install
    node: precise

    builders:
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/select-mirror.sh openstack requirements
          virtualenv --clear .venv
          PIP_ARGS=""
          REQ_FILES="tools/pip-requires tools/test-requires requirements.txt test-requirements.txt"
          for FILE in $REQ_FILES
          do
            if [ -e $FILE ]
            then
              # Ignore lines beginning with https?:// just as the mirror script does.
              sed -e '/^https\?:\/\//d' $FILE > $FILE.clean
              PIP_ARGS="$PIP_ARGS -r $FILE.clean"
            fi
          done
          # Run the same basic pip command that the mirror script runs.
          .venv/bin/pip install -M -U --exists-action=w $PIP_ARGS

          # Print all installed stuff to demonstrate versions
          .venv/bin/pip freeze

    publishers:
      - console-log
