- job-template:
    name: '{pipeline}-requirements-integration-dsvm'
    node: '{node}'

    wrappers:
      - build-timeout:
          timeout: 125
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=120
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          export DEVSTACK_GATE_REQS_INTEGRATION=1
          export PIP_PROCESS_DEPENDENCY_LINKS=1
          function gate_hook {{
              set -x
              bash $BASE/new/devstack-gate/devstack-vm-gate.sh && \
              bash -xe $BASE/new/pbr/tools/integration.sh $(cat $BASE/new/requirements/projects.txt)
          }}
          export -f gate_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log

- job:
    name: propose-requirements-updates
    node: proposal

    builders:
      - revoke-sudo
      - link-logs
      - net-info
      - gerrit-git-prep
      - shell: /usr/local/jenkins/slave_scripts/propose_update.sh requirements

    publishers:
      - console-log
