- job:
    name: 'gate-solum-devstack-dsvm'
    node: 'devstack-precise || devstack-trusty'

    wrappers:
      - build-timeout:
          timeout: 65
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=60
          export DEVSTACK_GATE_NEUTRON=1
          export ENABLED_SERVICES=solum,solum-api,solum-build-api,solum-conductor,solum-deployer,solum-worker,tempest,zaqar,barbican,mistral
          export PROJECTS="stackforge/solum $PROJECTS"
          # TODO(ravips): Workaround until barbican, mistral gets into devstack
          export PROJECTS="openstack/barbican stackforge/mistral $PROJECTS"

          function pre_test_hook {
              cd /opt/stack/new/solum/functionaltests
              ./pre_test_hook.sh
          }
          export -f pre_test_hook

          function gate_hook {
              cd /opt/stack/new/solum/functionaltests
              ./gate_hook.sh
          }
          export -f gate_hook

          function post_test_hook {
              cd /opt/stack/new/solum/functionaltests
              ./post_test_hook.sh
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log

- job:
    name: 'gate-solum-devstack-dsvm-f20'
    node: 'devstack-f20'

    wrappers:
      - build-timeout:
          timeout: 65
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=60
          export DEVSTACK_GATE_NEUTRON=1
          export ENABLED_SERVICES=solum,solum-api,solum-build-api,solum-conductor,solum-deployer,solum-worker,tempest,zaqar,barbican,mistral
          export PROJECTS="stackforge/solum $PROJECTS"
          # TODO(ravips): Workaround until barbican, mistral gets into devstack
          export PROJECTS="openstack/barbican stackforge/mistral $PROJECTS"

          function pre_test_hook {
              cd /opt/stack/new/solum/functionaltests
              ./pre_test_hook.sh
          }
          export -f pre_test_hook

          function gate_hook {
              cd /opt/stack/new/solum/functionaltests
              ./gate_hook.sh
          }
          export -f gate_hook

          function post_test_hook {
              cd /opt/stack/new/solum/functionaltests
              ./post_test_hook.sh
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log
