- job:
    name: gate-storyboard-webclient-unittests
    node: bare-precise

    builders:
      - gerrit-git-prep
      - shell: |
          ./bin/bootstrap.sh
          ./bin/build.sh
    publishers:
      - console-log
      - coverage-log
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$LOG_PATH'
              source: './reports/**'
              keep-hierarchy: true
              copy-after-failure: true

- job-template:
    name: 'storyboard-webclient-release-{branch-designator}'
    node: bare-precise

    builders:
      - gerrit-git-prep
      - shell: |
          ./bin/bootstrap.sh
          ./bin/build.sh
      - shell: |
          #!/bin/bash -xe

          BRANCH={branch-designator}
          ARCHIVE_NAME={name}
          if [ "$BRANCH" != "master" ] ; then
              BRANCH_PATH=`echo $ZUUL_REFNAME | tr / -`
              ARCHIVE_NAME={name}-$BRANCH_PATH
          fi
          tar -czf $ARCHIVE_NAME.tar.gz dist/
          mv $ARCHIVE_NAME.tar.gz dist/
    publishers:
      - console-log
      - coverage-log
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$LOG_PATH'
              source: './reports/**'
              keep-hierarchy: true
              copy-after-failure: true
      - tarball:
          project: '{name}'
          site: '{tarball-site}'