# This is a non-standard docs job because it uses SCP instead of FTP
- job:
    name: storyboard-docs
    node: bare-precise

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - docs:
          github-org: openstack-infra
          project: storyboard

    publishers:
      - scp:
          site: '173.203.107.207'
          files:
            - target: 'ci/storyboard'
              source: 'doc/build/html/**/*'
              keep-hierarchy: true
      - console-log
