- job-template:
    name: '{pipeline}-swift-devstack-vm-functional'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0

          function post_test_hook {{
              cd /opt/stack/new/swift
              # Launch V2 auth tests and v1 tests after.
              bash .functests --verbosity=3 && \
                  SWIFT_TEST_CONFIG_FILE=/opt/stack/new/swift/test/sample.conf \
                      bash .functests --verbosity=3
          }}
          export -f post_test_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs
      - console-log


- job-template:
    name: 'periodic-swift-devstack-vm-functional-stable-{release}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    builders:
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          export ZUUL_BRANCH=stable/{release}
          unset ZUUL_PROJECT

          function post_test_hook {{
              cd /opt/stack/new/swift
              # Launch V2 auth tests and v1 tests after.
              bash .functests --verbosity=3 && \
                  SWIFT_TEST_CONFIG_FILE=/opt/stack/new/swift/test/sample.conf \
                      bash .functests --verbosity=3
          }}
          export -f post_test_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - devstack-logs-periodic
      - console-log-periodic
      - email:
          recipients: openstack-qa@lists.openstack.org
