- job-template:
    name: '{pipeline}-swift-dsvm-functional{branch-designator}'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 95
          fail: true
      - timestamps

    builders:
      - link-logs
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=90
          export FUNCTEST_TIMEOUT=30
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0
          export BRANCH_OVERRIDE={branch-override}
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function post_test_hook {{
              cd /opt/stack/new/swift
              # Launch V2 auth tests and v1 tests after.
              timeout -s 9 ${{FUNCTEST_TIMEOUT}}m bash .functests --verbosity=3 && \
                  SWIFT_TEST_CONFIG_FILE=/opt/stack/new/swift/test/sample.conf \
                      timeout -s 9 ${{FUNCTEST_TIMEOUT}}m bash .functests --verbosity=3
          }}
          export -f post_test_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log
