- job:
    name: gate-swift-devstack-vm-functional
    node: devstack-precise

    wrappers:
      - timeout:
          timeout: 120
          fail: true
      - timestamps

    parameters:
      - label:
          name: NODE_LABEL
          description: Label of node to use for this build
          default: devstack-precise

    builders:
      - devstack-inprogress
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_EXERCISES=0

          function post_test_hook {
              cd /opt/stack/new/swift
              # Launch V2 auth tests and v1 tests after.
              bash .functests && \
                  SWIFT_TEST_CONFIG_FILE=/opt/stack/new/swift/test/sample.conf \
                      bash .functests
          }
          export -f post_test_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs

    publishers:
      - console-log
      - devstack-complete
