- job-template:
    name: '{name}-upstream-translation-update'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/upstream_translation_update.sh {name}

    publishers:
      - console-log

    node: 'proposal'

- job-template:
    name: '{name}-propose-translation-update'

    builders:
      - revoke-sudo
      - branch-git-prep:
          branch: master
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/propose_translation_update.sh {name}

    publishers:
      - console-log

    node: 'proposal'

- job:
    name: 'django_openstack_auth-upstream-translation-update'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/upstream_translation_django_openstack_auth.sh

    publishers:
      - console-log

    node: 'proposal'

- job:
    name: 'django_openstack_auth-propose-translation-update'

    builders:
      - revoke-sudo
      - branch-git-prep:
          branch: master
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/propose_translation_update_django_openstack_auth.sh

    publishers:
      - console-log

    node: 'proposal'

- job:
    name: 'horizon-upstream-translation-update'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/upstream_translation_horizon.sh

    publishers:
      - console-log

    node: 'proposal'

- job:
    name: 'horizon-propose-translation-update'

    builders:
      - revoke-sudo
      - branch-git-prep:
          branch: master
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/propose_translation_update_horizon.sh

    publishers:
      - console-log

    node: 'proposal'

- job-template:
    name: '{name}-manuals-upstream-translation-update'

    builders:
      - revoke-sudo
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/upstream_translation_update_manuals.sh {name}

    publishers:
      - console-log

    node: 'proposal'

- job-template:
    name: '{name}-manuals-propose-translation-update'

    builders:
      - revoke-sudo
      - branch-git-prep:
          branch: master
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/propose_translation_update_manuals.sh {name}

    publishers:
      - console-log

    node: 'proposal'

- job-group:
    name: translation-jobs
    jobs:
      - '{name}-upstream-translation-update'
      - '{name}-propose-translation-update'

- job-group:
    name: manual-translation-jobs
    jobs:
      - '{name}-manuals-upstream-translation-update'
      - '{name}-manuals-propose-translation-update'
      - 'gate-{name}-tox-{envlist}':
          envlist: checklang
      - '{name}-tox-doc-{envlist}':
          envlist: publishlang
