- job-template:
    name: '{name}-upstream-translation-update'
    concurrent: false

    builders:
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/upstream_translation_update.sh {name}

    publishers:
      - console-log

    node: 'proposal'

- job-template:
    name: '{name}-propose-translation-update'
    concurrent: false

    builders:
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/propose_translation_update.sh {name}

    publishers:
      - console-log-periodic

    scm:
      - git:
          url: 'git://github.com/{github-org}/{name}.git'
          branches:
            - 'origin/master'

    node: 'proposal'

- job:
    name: manuals-upstream-translation-update
    concurrent: false

    builders:
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/upstream_translation_update_manuals.sh

    publishers:
      - console-log

    node: 'proposal'

- job:
    name: manuals-propose-translation-update
    concurrent: false

    builders:
      - shell: |
          #!/bin/bash -xe
          /usr/local/jenkins/slave_scripts/propose_translation_update_manuals.sh

    publishers:
      - console-log-periodic

    scm:
      - git:
          url: 'git://github.com/openstack/openstack-manuals.git'
          branches:
            - 'origin/master'

    node: 'proposal'

- job-group:
    name: translation-jobs
    jobs:
      - '{name}-upstream-translation-update'
      - '{name}-propose-translation-update'

