- job-template:
    name: 'gate-trove-buildimage-{datastore}'
    node: 'bare-precise || bare-trusty'

    builders:
      - link-logs
      - net-info
      - gerrit-git-prep
      - shell: |
          #!/bin/bash -xe
          sudo mkdir -p /opt/trove-image-build
          sudo chown $(whoami) /opt/trove-image-build
          export DEST=/opt/trove-image-build
          export KEY_DIR=`pwd`/scripts/files/keys
          cd scripts
          ./redstack build-image {datastore}
          mv $HOME/images/ubuntu_{datastore}/ubuntu_{datastore}.qcow2 $WORKSPACE/{datastore}.qcow2

    publishers:
      - scp:
          site: 'tarballs.openstack.org'
          files:
            - source: '{datastore}.qcow2'
              target: 'tarballs/trove/images/ubuntu'
              keep-hierarchy: false
              copy-after-failure: false
      - console-log


- job-template:
    name: 'gate-trove-functional-dsvm-{datastore}'
    node: 'devstack-precise || devstack-trusty'

    wrappers:
      - build-timeout:
          timeout: 95
      - timestamps

    builders:
      - link-logs
      - net-info
      - devstack-checkout
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=90
          export ENABLED_SERVICES=tempest,s-proxy,s-object,s-container,s-account,trove,tr-api,tr-tmgr,tr-cond
          export PROJECTS="openstack/trove-integration openstack/diskimage-builder openstack/tripleo-image-elements $PROJECTS"

          function post_test_hook {{
              export BRIDGE_IP=10.1.0.1
              export DEST=$BASE/new
              export PATH_DEVSTACK_SRC=$DEST/devstack
              cd /opt/stack/new/trove-integration/scripts
              ./redstack dsvm-gate-tests {datastore}
          }}
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh

    publishers:
      - devstack-logs
      - console-log
