# This is a non-standard docs job because it uses SCP instead of FTP
- job:
    name: zuul-docs
    node: precise

    builders:
      - gerrit-git-prep
      - docs:
          github-org: openstack-infra
          project: zuul

    publishers:
      - scp:
          site: '173.203.107.207'
          files:
            - target: 'ci/zuul'
              source: 'doc/build/html/**/*'
              keep-hierarchy: true
      - console-log

- job:
    name: 'dev-zuul-coverage'
    node: precise

    builders:
      - gerrit-git-prep
      - coverage:
          github-org: openstack-infra
          project: zuul

    publishers:
      - coverage-log
      - console-log

- job:
    name: 'periodic-test'

    wrappers:
      - timeout:
          timeout: 40
          fail: true
      - timestamps

    builders:
      - python27:
          github-org: 'openstack-infra'
          project: 'zuul'

    publishers:
      - test-results
      - console-log

    scm:
      - git:
          url: 'git://github.com/openstack-infra/zuul.git'
          branches:
            - 'origin/master'

    node: precise
