# This is a non-standard docs job because it uses SCP instead of FTP
- job:
    name: zuul-docs
    node: precise

    triggers:
      - zuul-post

    builders:
      - gerrit-git-prep
      - docs

    publishers:
      - scp:
          site: '173.203.107.207'
          files:
            - target: 'ci/zuul'
              source: 'doc/build/html/**/*'
              keep-hierarchy: true
      - console-log-post

- job:
    name: 'dev-zuul-coverage'
    node: 'precise'

    triggers:
      - zuul

    builders:
      - gerrit-git-prep
      - coverage

    publishers:
      - scp:
          site: 'static.openstack.org'
          files:
            - target: 'logs/$ZUUL_CHANGE/$ZUUL_PATCHSET/$ZUUL_PIPELINE/$JOB_NAME/$BUILD_NUMBER'
              source: 'cover/**'
              keep-hierarchy: true
              copy-after-failure: true
      - console-log-post
