- hosts: bridge.openstack.org
  tasks:
    - name: Register junit.xml file
      stat:
        path: "{{ zuul.project.src_dir }}/junit.xml"
      register: _junit

    - name: Collect testinfra logs
      synchronize:
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        src: "{{ zuul.project.src_dir }}/junit.xml"
        verify_host: true
      when: _junit.stat.exists|bool

    - name: Collect ansible configuration
      synchronize:
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        src: "/etc/ansible"
        verify_host: true
      ignore_errors: true
