- name: Install HWE kernel for arm64
  apt:
    name: linux-generic-hwe-16.04
    state: present

# This is copy pasta'd from Debian.yaml because
#   include_tasks: Debian.yaml
# Was here previously and resulted in this entire surrounding play
# stopping/crashing and ansible continued with the next play in the
# playbook as if nothing were wrong. This is concerning for a couple
# reasons, why doesnt include_tasks work? and why does it crash ansible
# without any reported failure.
- name: Remove packages that make no sense for our servers
  package:
    name:
      - whoopsie
      - popularity-contest
      - snapd
      - lxd
      - lxd-client
    state: absent

- name: Configure file limits
  copy:
    mode: 0644
    src: debian_limits.conf
    dest: /etc/security/limits.d/60-nofile-limit.conf

- name: Custom rsyslog config to disable /dev/xconsole noise
  copy:
    mode: 0644
    src: rsyslog.d_50-default.conf
    dest: /etc/rsyslog.d/50-default.conf
  notify: Restart rsyslog

- name: Install apt-daily 10periodic file for unattended-upgrades
  copy:
     mode: 0444
     src: 10periodic
     dest: /etc/apt/apt.conf.d/10periodic
     owner: root
     group: root

- name: Install 50unattended-upgrades file for unattended-upgrades
  copy:
     mode: 0444
     src: 50unattended-upgrades
     dest: /etc/apt/apt.conf.d/50unattended-upgrades
     owner: root
     group: root
