- name: Ensure directory exists for lock files
  file:
    state: directory
    path: /var/run/ansible

- name: Set up cron job for running run_cloud_launcher.sh
  cron:
    name: run_cloud_launcher.sh
    state: present
    job: '/usr/bin/flock -n /var/run/ansible/run_cloud_launcher.lock /bin/bash /opt/system-config/run_cloud_launcher.sh -c >> /var/log/ansible/run_cloud_launcher_cron.log 2>&1'
    minute: "{{ cloud_launcher_cron_interval.minute }}"
    hour: "{{ cloud_launcher_cron_interval.hour }}"
    day: "{{ cloud_launcher_cron_interval.day }}"
    month: "{{ cloud_launcher_cron_interval.month }}"
    weekday: "{{ cloud_launcher_cron_interval.weekday }}"

- name: Setup log rotation
  include_role:
    name: logrotate
  vars:
    logrotate_file_name: /var/log/ansible/run_cloud_launcher_cron.log
