# This file is not a playbook, is a YAML file containing the resources layouts
# for all the OpenStack Infra clouds.
# It is meant to be passed as an argument to the the Ansible cloud launcher.
profiles:
  # Profile to launch AFS server for nodepool.
  - name: openstackci-projects
    projects:
      - name: openstackci
        description: OpenStack CI project
        domain: default
      - name: openstackzuul
        description: OpenStack zuul project
        domain: default

  - name: openstackci-security
    security_groups:
      - name: default
        description: Default security group
    security_groups_rules:
      - security_group: default
        ethertype: IPv4
        remote_group: default
        state: absent
      - security_group: default
        ethertype: IPv6
        remote_group: default
        state: absent
      - security_group: default
        ethertype: IPv4
        remote_ip_prefix: 0.0.0.0/0
      - security_group: default
        ethertype: IPv6
        remote_ip_prefix: ::/0

  - name: openstackci-keypairs
    keypairs:
      - name: infra-root-keys
        public_key: |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCuP0CZE8AYnbm8gxecCxKeRw0wHRyryd+FKmNNsdr0d3UvfCbqNzLigrqEBZsKpofi3M4qCWNpKRyfhnjPynLTQjP1vnX9AbL9UGoiHxScfvh3skntTYMs9ezJRd0rMJJZO76FPo8bJLDlwxAQl8m/nuj3HfYiO5hYE7P+a3rhsJh4nEfBb7xh+Q5yM0PWObkkBl6IRiBYjlcsXNZHgTA5kNuihUk5bHqAw54sHh05DhpgOITpTw4LFbh4Ew2NKq49dEb2xbTuAyAr2DHNOGgIwKEZpwtKZEIGEuiLbb4DQRsfivrvyOjnK2NFjQzGyNOHfsOldWHRQwUKUs8nrxKdXvqcrfMnSVaibeYK2TRL+6jd9kc5SIhWI3XLm7HbX7uXMD7/JQrkL25Rcs6nndDCH72DJLz+ynA/T5umMbNBQ9tybL5z73IOpfShRGjQYego22CxDOy7e/5OEMHNoksbFb1S02viM9O2puS7LDqqfT9JIbbPqCrbRi/zOXo0f4EXo6xKUAmd8qlV+6f/p57/qFihzQDaRFVlFEH3k7qwsw7PYGUTwkPaThe6xyZN6D5jqxCZU3aSYu+FGb0oYo+M5IxOm0Cb4NNsvvkRPxWtwSayfFGu6+m/+/RyA3GBcAMev7AuyKN+K2vGMsLagHOx4i+5ZAcUwGzLeXAENNum3w== pabelanger@redhat.com

  - name: openstackci-flavors
    flavors:
      - name: nodepool
        ram: 8192
        vcpus: 8
        disk: 80
      - name: mirror
        ram: 8192
        vcpus: 4
        disk: 100

  - name: openstackci-images
    images:
      - name: ubuntu-trusty
        download_image_url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
        download_image_dest: /tmp/ubuntu-trusty.img
        filename: /tmp/ubuntu-trusty.img

  - name: admin-roles
    roles:
      - name: Member

  - name: openstackci-user-roles
    user_roles:
      - role: Member
        user: openstackci
        project: openstackci

  - name: openstackzuul-user-roles
    user_roles:
      - role: Member
        user: openstackzuul
        project: openstackzuul

clouds:
  # bluebox-sjc1
  - name: admin-bluebox
    profiles:
      - openstackci-projects
      - openstackci-flavors
  - name: openstackci-bluebox
    profiles:
      - openstackci-keypairs
      - openstackci-security
  - name: openstackzuul-bluebox
    profiles:
      - openstackci-keypairs
      - openstackci-security

  # osic-cloud1
  - name: openstackci-osic-cloud1
    profiles:
      - openstackci-keypairs
      - openstackci-security

  - name: openstackjenkins-osic-cloud1
    profiles:
      - openstackci-keypairs
      - openstackci-security

  # internap
  - name: openstackci-internap-mtl01
    oscc_cloud: openstackci-internap
    region_name: mtl01
    profiles:
      - openstackci-keypairs
      - openstackci-security
  - name: openstackjenkins-internap-mtl01
    oscc_cloud: openstackjenkins-internap
    region_name: mtl01
    profiles:
      - openstackci-keypairs
      - openstackci-security

  # rackspace
  - name: openstackci-rax-dfw
    oscc_cloud: openstackci-rax
    region_name: dfw
    profiles:
      - openstackci-keypairs
  - name: openstackjenkins-rax-dfw
    oscc_cloud: openstackjenkins-rax
    region_name: dfw
    profiles:
      - openstackci-keypairs
  - name: openstackci-rax-ord
    oscc_cloud: openstackci-rax
    region_name: ord
    profiles:
      - openstackci-keypairs
  - name: openstackjenkins-rax-ord
    oscc_cloud: openstackjenkins-rax
    region_name: ord
    profiles:
      - openstackci-keypairs
  - name: openstackci-rax-iad
    oscc_cloud: openstackci-rax
    region_name: iad
    profiles:
      - openstackci-keypairs
  - name: openstackjenkins-rax-iad
    oscc_cloud: openstackjenkins-rax
    region_name: iad
    profiles:
      - openstackci-keypairs

  # tripleo-test-cloud-rh1
  - name: openstackci-tripleo-test-cloud-rh1
    profiles:
      - openstackci-keypairs
      - openstackci-security
  - name: openstackzuul-tripleo-test-cloud-rh1
    profiles:
      - openstackci-keypairs
      - openstackci-security

  # infracloud-vanilla
  - name: admin-infracloud-vanilla
    profiles:
      - openstackci-projects
      - openstackci-flavors
      - admin-roles
      - openstackci-user-roles
      - openstackzuul-user-roles
  - name: openstackci-infracloud-vanilla
    profiles:
      - openstackci-keypairs
      - openstackci-security
      - openstackci-images
  - name: openstackzuul-infracloud-vanilla
    profiles:
      - openstackci-keypairs
      - openstackci-security

  # infracloud-chocolate
  - name: admin-infracloud-chocolate
    profiles:
      - openstackci-projects
      - openstackci-flavors
      - admin-roles
      - openstackci-user-roles
      - openstackzuul-user-roles
  - name: openstackci-infracloud-chocolate
    profiles:
      - openstackci-keypairs
      - openstackci-security
      - openstackci-images
  - name: openstackzuul-infracloud-chocolate
    profiles:
      - openstackci-keypairs
      - openstackci-security
