---
- hosts: localhost
  gather_facts: true
  connection: local
  tasks:
    # Note that git module does ls-remote if clone is set to no and places
    # the remote_head value in returndict.after
    - git: repo=https://git.openstack.org/openstack-infra/project-config clone=no
      register: gitinfo
  roles:
    - role: puppet
      copy_hieradata: False
- hosts: git0*
  gather_facts: true
  max_fail_percentage: 1
  roles:
    - role: puppet
      facts:
        project_config_ref: "{{ hostvars.localhost.gitinfo.after }}"
- hosts: review.openstack.org
  gather_facts: true
  roles:
    - role: puppet
      facts:
        project_config_ref: "{{ hostvars.localhost.gitinfo.after }}"
