---
- hosts: "controller*.ic.openstack.org:!disabled"
  gather_facts: true
  roles:
    - role: puppet
      manage_config: true
- hosts: "compute*.ic.openstack.org:!disabled"
  gather_facts: true
  roles:
    - role: puppet
      manage_config: true
