---
- hosts: "localhost:!disabled"
  strategy: free
  gather_facts: true
  connection: local
  tasks:
    # Note that git module does ls-remote if clone is set to no and places
    # the remote_head value in returndict.after
    - git: repo=https://git.openstack.org/openstack-infra/project-config clone=no version=master
      register: gitinfo
  roles:
    - role: puppet
      copy_hieradata: False
      copy_puppet: False
- hosts: "git0*:!disabled"
  strategy: free
  gather_facts: true
  max_fail_percentage: 1
  roles:
    - role: puppet
      facts:
        project_config_ref: "{{ hostvars.localhost.gitinfo.after }}"
- hosts: "review.openstack.org:!disabled"
  strategy: free
  gather_facts: true
  roles:
    - role: puppet
      facts:
        project_config_ref: "{{ hostvars.localhost.gitinfo.after }}"
      vars:
        puppet_timeout: 60m
