---
- hosts: "localhost:!disabled"
  connection: local
  gather_facts: false
  tasks:
  - git:
      repo: https://git.openstack.org/openstack-infra/system-config
      dest: /opt/system-config/production
      force: yes
      version: master
  - shell: ./install_modules.sh
    args:
      chdir: /opt/system-config/production
  - shell: ansible-galaxy install --force -r roles.yaml
    args:
      chdir: /opt/system-config/production
